export const a1Questions = [
  // A1 - Grammar (10 questions)
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Easy",
    text: "___ is your name?",
    options: ["What", "Who", "Where", "When"],
    correctOption: 0,
    hint: "Use the question word that asks for information about a thing.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Easy",
    text: "I ___ a student.",
    options: ["is", "are", "am", "be"],
    correctOption: 2,
    hint: "Which form of the verb 'to be' goes with the pronoun 'I'?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "She ___ from Spain.",
    options: ["are", "is", "am", "be"],
    correctOption: 1,
    hint: "Which form of 'to be' is used for 'he', 'she', or 'it'?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "They ___ English.",
    options: ["speak", "speaks", "speaking", "is speak"],
    correctOption: 0,
    hint: "For 'they', the base form of the verb is usually correct in the present tense.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "He ___ have a car.",
    options: ["don't", "isn't", "doesn't", "aren't"],
    correctOption: 2,
    hint: "For negative sentences with 'he', 'she', or 'it', we use a special helping verb.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "There ___ a book on the table.",
    options: ["is", "are", "am", "be"],
    correctOption: 0,
    hint: "Use 'is' for singular items and 'are' for plural items.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Hard",
    text: "Can you pass me ___ apple, please?",
    options: ["a", "an", "the", "some"],
    correctOption: 1,
    hint: "Which article do we use before a word that starts with a vowel sound?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Hard",
    text: "These are my ___.",
    options: ["friend", "friends", "friend's", "friends'"],
    correctOption: 1,
    hint: "When talking about more than one person, we usually add an 's' to the noun.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Easy",
    text: "I live ___ London.",
    options: ["in", "on", "at", "under"],
    correctOption: 0,
    hint: "Which preposition is used for cities, countries, and large areas?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Hard",
    text: "What time ___ you get up?",
    options: ["do", "does", "are", "is"],
    correctOption: 0,
    hint: "Which helping verb do we use to ask questions with 'you' in the present simple?",
  },

  // A1 - Vocabulary (10 questions)
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "The opposite of 'hot' is ___.",
    options: ["cold", "warm", "cool", "fire"],
    correctOption: 0,
    hint: "Think about the weather in winter.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "A cat says ___.",
    options: ["woof", "moo", "meow", "oink"],
    correctOption: 2,
    hint: "This is a common pet.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "What color is a banana?",
    options: ["Red", "Blue", "Green", "Yellow"],
    correctOption: 3,
    hint: "It's the color of the sun.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "You use a ___ to write.",
    options: ["chair", "pen", "fork", "bed"],
    correctOption: 1,
    hint: "It's a tool for putting words on paper.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "Which of these is a fruit?",
    options: ["Carrot", "Potato", "Apple", "Broccoli"],
    correctOption: 2,
    hint: "It's often red or green and grows on trees.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "Your mother's son is your ___.",
    options: ["sister", "uncle", "brother", "aunt"],
    correctOption: 2,
    hint: "This is a male sibling.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "What do you wear on your feet?",
    options: ["Hats", "Gloves", "Socks", "Scarves"],
    correctOption: 2,
    hint: "You usually put these on before your shoes.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The number after nine is ___.",
    options: ["eight", "seven", "ten", "eleven"],
    correctOption: 2,
    hint: "Count from one to ten.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "Which of these is a room in a house?",
    options: ["Garage", "Garden", "Kitchen", "Street"],
    correctOption: 2,
    hint: "This is where you cook food.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "A baby dog is called a ___.",
    options: ["kitten", "puppy", "calf", "chick"],
    correctOption: 1,
    hint: "This is a young canine.",
  },

  // A1 - Reading (10 questions)
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the text: 'My name is John. I am a doctor.' What is John's job?",
    options: ["Teacher", "Student", "Doctor", "Engineer"],
    correctOption: 2,
    hint: "The text says 'I am a...'",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the sign: 'STOP'. What should you do?",
    options: ["Go faster", "Stop moving", "Look left", "Continue"],
    correctOption: 1,
    hint: "The word itself is a command.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'I have a cat and a dog. The cat is black.' What color is the cat?",
    options: ["White", "Brown", "Black", "The text doesn't say"],
    correctOption: 2,
    hint: "Find the sentence that describes the cat.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the menu: 'Cheeseburger - $5, Soda - $2'. How much is a cheeseburger?",
    options: ["$2", "$5", "$7", "$3"],
    correctOption: 1,
    hint: "Look for the price next to the word 'Cheeseburger'.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the email: 'Hi Sarah, The meeting is at 3 PM. Thanks, Tom.' When is the meeting?",
    options: ["In the morning", "At 3 PM", "At 3 AM", "Tomorrow"],
    correctOption: 1,
    hint: "The email explicitly states the time.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'Maria likes apples, but she does not like oranges.' Which fruit does Maria NOT like?",
    options: ["Apples", "Bananas", "Oranges", "Grapes"],
    correctOption: 2,
    hint: "The text uses 'but she does not like...' to show a preference.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'The library is closed on Sundays.' Can you go to the library on Sunday?",
    options: ["Yes", "No", "Only in the morning", "Maybe"],
    correctOption: 1,
    hint: "What does 'closed' mean?",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'He wears a blue shirt and white shoes.' What color are his shoes?",
    options: ["Blue", "Red", "Black", "White"],
    correctOption: 3,
    hint: "Find the part of the sentence that talks about shoes.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the sign: 'Exit'. Where does this sign lead?",
    options: ["To the entrance", "To the way out", "To the bathroom", "To the manager's office"],
    correctOption: 1,
    hint: "This word means to leave a place.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'My brother is tall. He has short hair.' What is his hair like?",
    options: ["Long", "Blonde", "Short", "Curly"],
    correctOption: 2,
    hint: "The second sentence describes his hair.",
  },

  // A1 - Listening (10 questions)
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'Hello!').' Choose the correct greeting.",
    options: ["Goodbye", "Hello", "Thank you", "Sorry"],
    correctOption: 1,
    hint: "This is a common way to start a conversation.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'My favorite color is blue.').' What is the favorite color?",
    options: ["Red", "Green", "Blue", "Yellow"],
    correctOption: 2,
    hint: "The speaker names a specific color.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'Can I have a coffee, please?').' What does the person want?",
    options: ["Tea", "Water", "Coffee", "Juice"],
    correctOption: 2,
    hint: "The person is ordering a drink.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'It's a sunny day.').' What is the weather like?",
    options: ["Rainy", "Snowy", "Windy", "Sunny"],
    correctOption: 3,
    hint: "This weather is associated with the sun.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'My flight is at ten thirty.').' What is the flight time?",
    options: ["10:00", "10:30", "11:00", "11:30"],
    correctOption: 1,
    hint: "'Thirty' often means 30 minutes past the hour.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'I have two brothers and one sister.').' How many sisters does the person have?",
    options: ["One", "Two", "Three", "None"],
    correctOption: 0,
    hint: "Listen for the number before the word 'sister'.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'The number is five.').' Choose the number you heard.",
    options: ["2", "5", "8", "10"],
    correctOption: 1,
    hint: "This is the number between four and six.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I am from Canada.').' Where is the person from?",
    options: ["The USA", "The UK", "Australia", "Canada"],
    correctOption: 3,
    hint: "The speaker names a country in North America.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'Excuse me, where is the train station?').' What is the person looking for?",
    options: ["A bus stop", "A hotel", "A train station", "A restaurant"],
    correctOption: 2,
    hint: "The person is asking for directions to a place with trains.",
  },
  {
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I don't like cheese.').' Does the person like cheese?",
    options: ["Yes", "No", "Maybe", "Sometimes"],
    correctOption: 1,
    hint: "The phrase 'I don't like' is a negation.",
  },

  // A1 - Speaking (10 questions)
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Easy",
    text: "How would you introduce yourself? Choose the best phrase.",
    options: ["My name is...", "You are...", "I am from...", "It is..."],
    correctOption: 0,
    hint: "This is the most common way to tell someone your name.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Easy",
    text: "Someone says 'Thank you.' What is the best reply?",
    options: ["Please.", "I am fine.", "You're welcome.", "Goodbye."],
    correctOption: 2,
    hint: "This is a polite response to being thanked.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "You want to know the time. What do you ask?",
    options: ["What time is it?", "How are you?", "Where is the bank?", "What is this?"],
    correctOption: 0,
    hint: "This question directly asks for the current time.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the best way to order a coffee in a cafe.",
    options: ["Give me coffee.", "Coffee!", "I want coffee.", "Can I have a coffee, please?"],
    correctOption: 3,
    hint: "Politeness is key. Using 'Can I have...' and 'please' is very common.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Hard",
    text: "Someone asks 'How are you?' What is a typical, positive response?",
    options: ["I am a teacher.", "I am at home.", "I'm fine, thanks.", "My name is Paul."],
    correctOption: 2,
    hint: "This phrase is used to say you are feeling good.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you say goodbye to a friend?",
    options: ["Hello!", "Nice to meet you.", "See you later!", "What's up?"],
    correctOption: 2,
    hint: "This is an informal way to say you will see them again.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Easy",
    text: "You don't understand something. What can you say?",
    options: ["I don't know.", "I'm sorry, I don't understand.", "It's okay.", "Yes, I do."],
    correctOption: 1,
    hint: "This is a polite way to ask for clarification.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the best question to ask about someone's job.",
    options: ["What your job?", "What do you do?", "You work?", "Where is your job?"],
    correctOption: 1,
    hint: "'What do you do?' is a very common and natural way to ask this.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you agree with someone's simple opinion, like 'It's a beautiful day'?",
    options: ["I not agree.", "No, it isn't.", "Yes, it is.", "Why?"],
    correctOption: 2,
    hint: "A simple affirmation using the verb 'to be' works well here.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the best way to ask for the price of an item.",
    options: ["How much is it?", "What price?", "Is it expensive?", "I want to pay."],
    correctOption: 0,
    hint: "This is the standard question for asking about cost.",
  },

  // A1 - Writing (10 questions)
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Easy",
    text: "Choose the correct punctuation to end a sentence.",
    options: [",", ".", "?", "!"],
    correctOption: 1,
    hint: "This mark is called a period or a full stop.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Easy",
    text: "Which of these words should start with a capital letter?",
    options: ["day", "london", "cat", "book"],
    correctOption: 1,
    hint: "Names of cities, people, and countries always start with a capital letter.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "How do you write the first person pronoun?",
    options: ["i", "Me", "I", "my"],
    correctOption: 2,
    hint: "When 'I' is by itself, it is always a capital letter.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "Choose the correctly written sentence.",
    options: ["he is from france", "He is from france.", "he is from France.", "He is from France."],
    correctOption: 3,
    hint: "Sentences must start with a capital letter and end with punctuation. Countries are proper nouns.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Hard",
    text: "You are writing a short email to a friend. How should you start?",
    options: ["Dear Sir,", "To whom it may concern,", "Hi [Friend's Name],", "Attention:"],
    correctOption: 2,
    hint: "For informal emails, a simple 'Hi' or 'Hello' followed by the name is best.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Hard",
    text: "Which sentence correctly uses 'a' and 'an'?",
    options: ["I have a dog and an cat.", "I have an dog and a cat.", "I have a dog and a cat.", "I have an dog and an cat."],
    correctOption: 2,
    hint: "Use 'an' before words that start with a vowel sound (a, e, i, o, u).",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Easy",
    text: "What do you put at the end of a question?",
    options: [".", "!", ",", "?"],
    correctOption: 3,
    hint: "This is called a question mark.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "Choose the correct possessive form: 'The book belongs to Tom.'",
    options: ["Toms book", "Tom's book", "Toms' book", "Tom book's"],
    correctOption: 1,
    hint: "To show possession for a singular noun, we add an apostrophe 's'.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Hard",
    text: "Which sentence is correct?",
    options: ["They is happy.", "They're happy.", "Their happy.", "There happy."],
    correctOption: 1,
    hint: "'They're' is the short form of 'They are'.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "How do you list items in a sentence?",
    options: ["I like apples and oranges and bananas.", "I like apples, oranges, bananas.", "I like apples, oranges and bananas.", "I like: apples, oranges, bananas."],
    correctOption: 2,
    hint: "Use commas to separate items in a list, often with 'and' before the last item.",
  },
];
