export const a1Questions = [
  // A1 - Grammar (10 questions)
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Easy",
    text: "___ is your name?",
    options: ["What", "Who", "Where", "When"],
    correctOption: 0,
    hint: "Usa a palavra de pergunta que pede informações sobre uma coisa.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Easy",
    text: "I ___ a student.",
    options: ["is", "are", "am", "be"],
    correctOption: 2,
    hint: "Qual a forma do verbo 'to be' que acompanha o pronome 'I'?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "She ___ from Spain.",
    options: ["are", "is", "am", "be"],
    correctOption: 1,
    hint: "Qual a forma do 'to be' que é usada para 'he', 'she' ou 'it'?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "They ___ English.",
    options: ["speak", "speaks", "speaking", "is speak"],
    correctOption: 0,
    hint: "Para 'they', a forma base do verbo é geralmente a correta no presente.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "He ___ have a car.",
    options: ["don't", "isn't", "doesn't", "aren't"],
    correctOption: 2,
    hint: "Para frases negativas com 'he', 'she' ou 'it', usamos um verbo auxiliar especial.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Medium",
    text: "There ___ a book on the table.",
    options: ["is", "are", "am", "be"],
    correctOption: 0,
    hint: "Usa 'is' para itens no singular e 'are' para itens no plural.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Hard",
    text: "Can you pass me ___ apple, please?",
    options: ["a", "an", "the", "some"],
    correctOption: 1,
    hint: "Qual artigo usamos antes de uma palavra que começa com som de vogal?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Hard",
    text: "These are my ___.",
    options: ["friend", "friends", "friend's", "friends'"],
    correctOption: 1,
    hint: "Quando falamos de mais de uma pessoa, geralmente adicionamos um 's' ao substantivo.",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Easy",
    text: "I live ___ London.",
    options: ["in", "on", "at", "under"],
    correctOption: 0,
    hint: "Qual preposição é usada para cidades, países e áreas grandes?",
  },
  {
    cefrLevel: "A1",
    area: "Grammar",
    difficulty: "Hard",
    text: "What time ___ you get up?",
    options: ["do", "does", "are", "is"],
    correctOption: 0,
    hint: "Qual verbo auxiliar usamos para fazer perguntas com 'you' no presente simples?",
  },

  // A1 - Vocabulary (10 questions)
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "The opposite of 'hot' is ___.",
    options: ["cold", "warm", "cool", "fire"],
    correctOption: 0,
    hint: "Pensa no tempo no inverno.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "A cat says ___.",
    options: ["woof", "moo", "meow", "oink"],
    correctOption: 2,
    hint: "Este é um animal de estimação comum.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "What color is a banana?",
    options: ["Red", "Blue", "Green", "Yellow"],
    correctOption: 3,
    hint: "É a cor do sol.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "You use a ___ to write.",
    options: ["chair", "pen", "fork", "bed"],
    correctOption: 1,
    hint: "É uma ferramenta para colocar palavras no papel.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "Which of these is a fruit?",
    options: ["Carrot", "Potato", "Apple", "Broccoli"],
    correctOption: 2,
    hint: "É muitas vezes vermelha ou verde e cresce em árvores.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "Your mother's son is your ___.",
    options: ["sister", "uncle", "brother", "aunt"],
    correctOption: 2,
    hint: "Este é um irmão do sexo masculino.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "What do you wear on your feet?",
    options: ["Hats", "Gloves", "Socks", "Scarves"],
    correctOption: 2,
    hint: "Geralmente calças isto antes dos sapatos.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The number after nine is ___.",
    options: ["eight", "seven", "ten", "eleven"],
    correctOption: 2,
    hint: "Conta de um a dez.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "Which of these is a room in a house?",
    options: ["Garage", "Garden", "Kitchen", "Street"],
    correctOption: 2,
    hint: "É aqui que cozinhas a comida.",
  },
  {
    cefrLevel: "A1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "A baby dog is called a ___.",
    options: ["kitten", "puppy", "calf", "chick"],
    correctOption: 1,
    hint: "Este é um canino jovem.",
  },

  // A1 - Reading (10 questions)
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the text: 'My name is John. I am a doctor.' What is John's job?",
    options: ["Teacher", "Student", "Doctor", "Engineer"],
    correctOption: 2,
    hint: "O texto diz 'I am a...'",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the sign: 'STOP'. What should you do?",
    options: ["Go faster", "Stop moving", "Look left", "Continue"],
    correctOption: 1,
    hint: "A própria palavra é um comando.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'I have a cat and a dog. The cat is black.' What color is the cat?",
    options: ["White", "Brown", "Black", "The text doesn't say"],
    correctOption: 2,
    hint: "Encontra a frase que descreve o gato.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the menu: 'Cheeseburger - $5, Soda - $2'. How much is a cheeseburger?",
    options: ["$2", "$5", "$7", "$3"],
    correctOption: 1,
    hint: "Procura o preço ao lado da palavra 'Cheeseburger'.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the email: 'Hi Sarah, The meeting is at 3 PM. Thanks, Tom.' When is the meeting?",
    options: ["In the morning", "At 3 PM", "At 3 AM", "Tomorrow"],
    correctOption: 1,
    hint: "O e-mail indica explicitamente a hora.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'Maria likes apples, but she does not like oranges.' Which fruit does Maria NOT like?",
    options: ["Apples", "Bananas", "Oranges", "Grapes"],
    correctOption: 2,
    hint: "O texto usa 'but she does not like...' para mostrar uma preferência.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'The library is closed on Sundays.' Can you go to the library on Sunday?",
    options: ["Yes", "No", "Only in the morning", "Maybe"],
    correctOption: 1,
    hint: "O que significa 'closed'?",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'He wears a blue shirt and white shoes.' What color are his shoes?",
    options: ["Blue", "Red", "Black", "White"],
    correctOption: 3,
    hint: "Encontra a parte da frase que fala sobre sapatos.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the sign: 'Exit'. Where does this sign lead?",
    options: ["To the entrance", "To the way out", "To the bathroom", "To the manager's office"],
    correctOption: 1,
    hint: "Esta palavra significa sair de um lugar.",
  },
  {
    cefrLevel: "A1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'My brother is tall. He has short hair.' What is his hair like?",
    options: ["Long", "Blonde", "Short", "Curly"],
    correctOption: 2,
    hint: "A segunda frase descreve o cabelo dele.",
  },

  // A1 - Listening (10 questions)
  {
    slug: "listening-a1-01",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'Hello!').' Choose the correct greeting.",
    options: ["Goodbye", "Hello", "Thank you", "Sorry"],
    correctOption: 1,
    hint: "Esta é uma forma comum de começar uma conversa.",
  },
  {
    slug: "listening-a1-02",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'My favorite color is blue.').' What is the favorite color?",
    options: ["Red", "Green", "Blue", "Yellow"],
    correctOption: 2,
    hint: "O orador menciona uma cor específica.",
  },
  {
    slug: "listening-a1-03",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'Can I have a coffee, please?').' What does the person want?",
    options: ["Tea", "Water", "Coffee", "Juice"],
    correctOption: 2,
    hint: "A pessoa está a pedir uma bebida.",
  },
  {
    slug: "listening-a1-04",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'It's a sunny day.').' What is the weather like?",
    options: ["Rainy", "Snowy", "Windy", "Sunny"],
    correctOption: 3,
    hint: "Este tempo está associado ao sol.",
  },
  {
    slug: "listening-a1-05",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'My flight is at ten thirty.').' What is the flight time?",
    options: ["10:00", "10:30", "11:00", "11:30"],
    correctOption: 1,
    hint: "'Thirty' significa muitas vezes 30 minutos depois da hora.",
  },
  {
    slug: "listening-a1-06",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'I have two brothers and one sister.').' How many sisters does the person have?",
    options: ["One", "Two", "Three", "None"],
    correctOption: 0,
    hint: "Ouve o número antes da palavra 'sister'.",
  },
  {
    slug: "listening-a1-07",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'The number is five.').' Choose the number you heard.",
    options: ["2", "5", "8", "10"],
    correctOption: 1,
    hint: "Este é o número entre quatro e seis.",
  },
  {
    slug: "listening-a1-08",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I am from Canada.').' Where is the person from?",
    options: ["The USA", "The UK", "Australia", "Canada"],
    correctOption: 3,
    hint: "O orador menciona um país na América do Norte.",
  },
  {
    slug: "listening-a1-09",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'Excuse me, where is the train station?').' What is the person looking for?",
    options: ["A bus stop", "A hotel", "A train station", "A restaurant"],
    correctOption: 2,
    hint: "A pessoa está a pedir direções para um local com comboios.",
  },
  {
    slug: "listening-a1-10",
    cefrLevel: "A1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I don't like cheese.').' Does the person like cheese?",
    options: ["Yes", "No", "Maybe", "Sometimes"],
    correctOption: 1,
    hint: "A frase 'I don't like' é uma negação.",
  },

  // A1 - Speaking (10 questions)
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Easy",
    text: "How would you introduce yourself? Choose the best phrase.",
    options: ["My name is...", "You are...", "I am from...", "It is..."],
    correctOption: 0,
    hint: "Esta é a forma mais comum de dizer o teu nome a alguém.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Easy",
    text: "Someone says 'Thank you.' What is the best reply?",
    options: ["Please.", "I am fine.", "You're welcome.", "Goodbye."],
    correctOption: 2,
    hint: "Esta é uma resposta educada a um agradecimento.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "You want to know the time. What do you ask?",
    options: ["What time is it?", "How are you?", "Where is the bank?", "What is this?"],
    correctOption: 0,
    hint: "Esta pergunta questiona diretamente a hora atual.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the best way to order a coffee in a cafe.",
    options: ["Give me coffee.", "Coffee!", "I want coffee.", "Can I have a coffee, please?"],
    correctOption: 3,
    hint: "A educação é fundamental. Usar 'Can I have...' e 'please' é muito comum.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Hard",
    text: "Someone asks 'How are you?' What is a typical, positive response?",
    options: ["I am a teacher.", "I am at home.", "I'm fine, thanks.", "My name is Paul."],
    correctOption: 2,
    hint: "Esta frase é usada para dizer que te sentes bem.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you say goodbye to a friend?",
    options: ["Hello!", "Nice to meet you.", "See you later!", "What's up?"],
    correctOption: 2,
    hint: "Esta é uma forma informal de dizer que os verás novamente.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Easy",
    text: "You don't understand something. What can you say?",
    options: ["I don't know.", "I'm sorry, I don't understand.", "It's okay.", "Yes, I do."],
    correctOption: 1,
    hint: "Esta é uma forma educada de pedir um esclarecimento.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the best question to ask about someone's job.",
    options: ["What your job?", "What do you do?", "You work?", "Where is your job?"],
    correctOption: 1,
    hint: "'What do you do?' é uma forma muito comum e natural de perguntar isto.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you agree with someone's simple opinion, like 'It's a beautiful day'?",
    options: ["I not agree.", "No, it isn't.", "Yes, it is.", "Why?"],
    correctOption: 2,
    hint: "Uma afirmação simples usando o verbo 'to be' funciona bem aqui.",
  },
  {
    cefrLevel: "A1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the best way to ask for the price of an item.",
    options: ["How much is it?", "What price?", "Is it expensive?", "I want to pay."],
    correctOption: 0,
    hint: "Esta é a pergunta padrão para perguntar o custo.",
  },

  // A1 - Writing (10 questions)
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Easy",
    text: "Choose the correct punctuation to end a sentence.",
    options: [",", ".", "?", "!"],
    correctOption: 1,
    hint: "Este sinal chama-se ponto final.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Easy",
    text: "Which of these words should start with a capital letter?",
    options: ["day", "london", "cat", "book"],
    correctOption: 1,
    hint: "Nomes de cidades, pessoas e países começam sempre com letra maiúscula.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "How do you write the first person pronoun?",
    options: ["i", "Me", "I", "my"],
    correctOption: 2,
    hint: "Quando o 'I' está sozinho, é sempre uma letra maiúscula.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "Choose the correctly written sentence.",
    options: ["he is from france", "He is from france.", "he is from France.", "He is from France."],
    correctOption: 3,
    hint: "As frases devem começar com letra maiúscula e terminar com pontuação. Os países são nomes próprios.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Hard",
    text: "You are writing a short email to a friend. How should you start?",
    options: ["Dear Sir,", "To whom it may concern,", "Hi [Friend's Name],", "Attention:"],
    correctOption: 2,
    hint: "Para e-mails informais, o melhor é um simples 'Hi' ou 'Hello' seguido do nome.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Hard",
    text: "Which sentence correctly uses 'a' and 'an'?",
    options: ["I have a dog and an cat.", "I have an dog and a cat.", "I have a dog and a cat.", "I have an dog and an cat."],
    correctOption: 2,
    hint: "Usa 'an' antes de palavras que começam com um som de vogal (a, e, i, o, u).",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Easy",
    text: "What do you put at the end of a question?",
    options: [".", "!", ",", "?"],
    correctOption: 3,
    hint: "Isto chama-se ponto de interrogação.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "Choose the correct possessive form: 'The book belongs to Tom.'",
    options: ["Toms book", "Tom's book", "Toms' book", "Tom book's"],
    correctOption: 1,
    hint: "Para mostrar posse num substantivo singular, adicionamos um apóstrofo 's'.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Hard",
    text: "Which sentence is correct?",
    options: ["They is happy.", "They're happy.", "Their happy.", "There happy."],
    correctOption: 1,
    hint: "'They're' é a forma curta de 'They are'.",
  },
  {
    cefrLevel: "A1",
    area: "Writing",
    difficulty: "Medium",
    text: "How do you list items in a sentence?",
    options: ["I like apples and oranges and bananas.", "I like apples, oranges, bananas.", "I like apples, oranges and bananas.", "I like: apples, oranges, bananas."],
    correctOption: 2,
    hint: "Usa vírgulas para separar itens numa lista, muitas vezes com 'and' antes do último item.",
  },
];
