export const b1Questions = [
  // B1 - Grammar (10 questions)
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Easy",
    text: "I haven't seen that film ___. Is it any good?",
    options: ["already", "yet", "just", "ever"],
    correctOption: 1,
    hint: "Qual palavra é tipicamente usada no final de frases negativas no Present Perfect?",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Easy",
    text: "If I had more money, I ___ a new car.",
    options: ["will buy", "buy", "bought", "would buy"],
    correctOption: 3,
    hint: "Esta é uma frase de second conditional, usada para situações hipotéticas. Qual verbo modal usamos na oração de resultado?",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Medium",
    text: "She has been working here ___ ten years.",
    options: ["since", "for", "from", "in"],
    correctOption: 1,
    hint: "Usa 'for' para falar de uma duração de tempo e 'since' para falar de um ponto de partida.",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Medium",
    text: "You ___ be tired after such a long journey.",
    options: ["must", "can", "should", "have"],
    correctOption: 0,
    hint: "Qual verbo modal é usado para fazer uma dedução lógica ou uma suposição forte?",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Hard",
    text: "This is the book ___ I was telling you about.",
    options: ["who", "which", "where", "what"],
    correctOption: 1,
    hint: "Qual pronome relativo é usado para referir coisas ou objetos?",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Hard",
    text: "By the time we got there, the party ___ already finished.",
    options: ["has", "have", "had", "was"],
    correctOption: 2,
    hint: "Usa o Past Perfect para descrever uma ação que aconteceu antes de outra ação no passado.",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Medium",
    text: "He's used ___ up early for his job.",
    options: ["to get", "get", "getting", "to getting"],
    correctOption: 2,
    hint: "A estrutura 'be used to' é seguida por um gerúndio (forma -ing) para falar de algo a que estás habituado.",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Easy",
    text: "You don't ___ to come if you don't want to.",
    options: ["must", "should", "have", "ought"],
    correctOption: 2,
    hint: "Qual verbo completa a frase que expressa falta de obrigação?",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Medium",
    text: "While I ___ for the bus, it started to rain.",
    options: ["waited", "was waiting", "am waiting", "wait"],
    correctOption: 1,
    hint: "Usa o past continuous para uma ação de fundo mais longa que foi interrompida por uma ação mais curta.",
  },
  {
    cefrLevel: "B1",
    area: "Grammar",
    difficulty: "Hard",
    text: "If you ___ me, I wouldn't have known about the problem.",
    options: ["hadn't told", "didn't tell", "wouldn't tell", "haven't told"],
    correctOption: 0,
    hint: "Esta é uma frase de third conditional, para situações hipotéticas do passado. A oração 'if' usa o Past Perfect.",
  },

  // B1 - Vocabulary (10 questions)
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "I need to ___ a flight to New York for next month.",
    options: ["book", "read", "do", "write"],
    correctOption: 0,
    hint: "Este verbo significa reservar ou fazer uma reserva.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "She's very ___. You can always trust her to do what she says.",
    options: ["reliable", "sociable", "sensitive", "creative"],
    correctOption: 0,
    hint: "Este adjetivo descreve alguém que é de confiança e com quem se pode contar.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "Could you please ___ me a favour and post this letter?",
    options: ["make", "give", "do", "take"],
    correctOption: 2,
    hint: "Esta é uma expressão comum: 'do someone a favour' (fazer um favor a alguém).",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The government plans to ___ new policies to improve public transport.",
    options: ["invent", "implement", "discover", "display"],
    correctOption: 1,
    hint: "Este verbo significa colocar uma decisão, plano ou acordo em vigor.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "It's important to set realistic ___ so you don't get disappointed.",
    options: ["goals", "rules", "laws", "games"],
    correctOption: 0,
    hint: "Esta palavra significa um objetivo ou resultado desejado.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "I was very ___ of my final exam results.",
    options: ["proud", "ashamed", "guilty", "nervous"],
    correctOption: 0,
    hint: "Este adjetivo descreve um sentimento de profundo prazer ou satisfação.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "It took him a long time to ___ from his illness.",
    options: ["recover", "discover", "cover", "remove"],
    correctOption: 0,
    hint: "Este verbo significa regressar a um estado normal de saúde, espírito ou força.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "What's the ___ like today? Is it sunny?",
    options: ["temperature", "climate", "weather", "atmosphere"],
    correctOption: 2,
    hint: "Esta palavra refere-se às condições atmosféricas num determinado momento e lugar.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "She has a very positive ___ on life.",
    options: ["aspect", "outlook", "opinion", "feature"],
    correctOption: 1,
    hint: "Esta palavra significa a atitude geral ou forma de pensar de uma pessoa sobre algo.",
  },
  {
    cefrLevel: "B1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The main ___ of this phone is its long battery life.",
    options: ["advantage", "quality", "character", "impression"],
    correctOption: 0,
    hint: "Esta palavra significa uma condição ou circunstância que coloca alguém numa posição favorável ou superior.",
  },

  // B1 - Reading (10 questions)
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the email: 'Dear staff, Please remember that the office will be closed on Monday for the public holiday.' Why will the office be closed?",
    options: ["For cleaning", "For a meeting", "For a public holiday", "For an emergency"],
    correctOption: 2,
    hint: "O e-mail indica um motivo específico para o encerramento.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the product review: 'The camera works well, although the battery life is quite short.' What is the main disadvantage of the product?",
    options: ["It's too expensive.", "It doesn't work well.", "The camera is bad.", "The battery doesn't last long."],
    correctOption: 3,
    hint: "A palavra 'although' é usada para introduzir um ponto de contraste ou negativo.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the article: 'The city council has announced plans to build a new bridge. Construction is expected to begin next year and will likely take three years.' How long will the construction take?",
    options: ["One year", "Two years", "Three years", "It's not mentioned"],
    correctOption: 2,
    hint: "Encontra a parte do texto que menciona a duração da construção.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'While some people prefer to work from home, others find the office environment more productive due to fewer distractions.' What is one benefit of working in an office mentioned in the text?",
    options: ["It's more comfortable", "You save money on transport", "There are fewer distractions", "The hours are more flexible"],
    correctOption: 2,
    hint: "O texto contrasta o trabalho a partir de casa com o trabalho num escritório. Procura a razão pela qual o escritório é considerado 'mais produtivo'.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the travel blog: 'Unless you book in advance, it's unlikely you'll find a hotel room during the festival.' What advice does the author give?",
    options: ["Don't go to the festival.", "Book your hotel early.", "Find a hotel when you arrive.", "Stay with friends."],
    correctOption: 1,
    hint: "A palavra 'unless' introduz uma condição. O que deves fazer para encontrar um quarto?",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the sign: 'Please do not feed the animals.' What are you asked not to do?",
    options: ["Take photos of the animals", "Give food to the animals", "Touch the animals", "Talk to the animals"],
    correctOption: 1,
    hint: "O verbo 'to feed' significa dar comida.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the advert: 'Our new language course is suitable for both beginners and intermediate learners.' Who is the course for?",
    options: ["Only beginners", "Only advanced learners", "Only intermediate learners", "Beginners and intermediate learners"],
    correctOption: 3,
    hint: "A expressão 'both...and...' é usada para incluir dois grupos diferentes.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the text message: 'Hi! Can you call me back when you're free? I need to ask you something.' What does the sender want you to do?",
    options: ["Send a text message", "Wait for them to call", "Telephone them later", "Forget about it"],
    correctOption: 2,
    hint: "'Call me back' é um pedido para retribuir uma chamada telefónica.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'The concert, which was supposed to be outdoors, was moved inside because of the heavy rain.' Why was the concert moved?",
    options: ["It was too sunny", "The band was late", "There were too many people", "Because of the bad weather"],
    correctOption: 3,
    hint: "O texto indica o motivo da mudança de local.",
  },
  {
    cefrLevel: "B1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'Employees who wish to apply for the new management position should submit their CV by Friday. Applicants must have at least five years of experience.' Who can apply for the job?",
    options: ["Any employee", "Only new employees", "Employees with 5+ years of experience", "Only the current managers"],
    correctOption: 2,
    hint: "O texto especifica uma condição necessária para os candidatos.",
  },

  // B1 - Listening (10 questions)
  {
    slug: "listening-b1-01",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'The flight to Berlin is now boarding at Gate 12.').' Where should passengers for Berlin go?",
    options: ["Gate 20", "Gate 12", "The check-in desk", "The exit"],
    correctOption: 1,
    hint: "O anúncio especifica o número da porta para o embarque.",
  },
  {
    slug: "listening-b1-02",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I'm sorry, but Dr. Smith is fully booked today. The earliest appointment we have is tomorrow morning.').' When can the person see the doctor?",
    options: ["Later today", "Right now", "Tomorrow morning", "Next week"],
    correctOption: 2,
    hint: "'Fully booked' significa que não há horários disponíveis. Qual é a primeira alternativa oferecida?",
  },
  {
    slug: "listening-b1-03",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I used to play a lot of football when I was younger, but I don't have time anymore.').' What is true about the speaker?",
    options: ["He still plays a lot of football.", "He never liked football.", "He doesn't play football now.", "He wants to start playing again."],
    correctOption: 2,
    hint: "A expressão 'used to' refere-se a um hábito passado que já não é verdade.",
  },
  {
    slug: "listening-b1-04",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'If you'd told me about the traffic, I would have left earlier.').' Why was the speaker late?",
    options: ["They left early.", "They didn't know about the traffic.", "The car broke down.", "They forgot about the meeting."],
    correctOption: 1,
    hint: "Esta é uma frase de third conditional que expressa um arrependimento passado. A pessoa está a imaginar uma ação passada diferente.",
  },
  {
    slug: "listening-b1-05",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'I'm not keen on spicy food, but I could go for a curry as long as it's a mild one.').' What kind of curry would the speaker eat?",
    options: ["A very spicy one", "A mild one", "Any kind of curry", "No curry at all"],
    correctOption: 1,
    hint: "'Not keen on' significa que ele não gosta muito. 'As long as' introduz uma condição que o tornaria aceitável.",
  },
  {
    slug: "listening-b1-06",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'Could you spell your surname for me, please?').' What does the listener want?",
    options: ["Your first name", "The letters of your last name", "Your address", "Your signature"],
    correctOption: 1,
    hint: "'Surname' é outra palavra para apelido ou nome de família. 'To spell' significa soletrar as letras.",
  },
  {
    slug: "listening-b1-07",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'The weather forecast says it's going to be sunny, but we might get a few showers in the afternoon.').' What is the weather forecast?",
    options: ["Rain all day", "Sunny all day", "Mainly sunny with some rain later", "Cloudy and cold"],
    correctOption: 2,
    hint: "A previsão menciona dois tipos diferentes de tempo em diferentes alturas do dia.",
  },
  {
    slug: "listening-b1-08",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'I've just finished reading a fantastic book. I'd really recommend it.').' What is the speaker's opinion of the book?",
    options: ["It was boring", "It was difficult to read", "They haven't finished it", "They thought it was excellent"],
    correctOption: 3,
    hint: "Palavras como 'fantastic' e 'recommend' mostram uma opinião muito positiva.",
  },
  {
    slug: "listening-b1-09",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'The total is twenty-five euros. Will you be paying by cash or card?').' What is the speaker asking?",
    options: ["How much it costs", "How the customer wants to pay", "If the customer has a discount", "If the customer wants a bag"],
    correctOption: 1,
    hint: "'Cash or card' refere-se ao método de pagamento.",
  },
  {
    slug: "listening-b1-10",
    cefrLevel: "B1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I'm looking forward to the holidays. I really need a break.').' How does the speaker feel about the holidays?",
    options: ["Anxious", "Excited", "Sad", "Indifferent"],
    correctOption: 1,
    hint: "A expressão 'looking forward to' exprime uma antecipação feliz.",
  },

  // B1 - Speaking (10 questions)
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Easy",
    text: "You are in a shop and you want to try on a jacket. What do you say?",
    options: ["Where can I try this on?", "I want this jacket.", "Is this jacket nice?", "How much to try?"],
    correctOption: 0,
    hint: "Esta pergunta questiona a localização dos provadores.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Someone asks for your opinion on a new film. How can you express a neutral or mixed opinion?",
    options: ["It was the best film ever!", "I hated it.", "It was okay, I suppose.", "I didn't see it."],
    correctOption: 2,
    hint: "Frases como 'it was okay' ou 'I suppose' mostram que não tens sentimentos fortes sobre o assunto.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the most natural way to ask for advice.",
    options: ["Give me advice.", "What you think I do?", "What should I do?", "Advise me now."],
    correctOption: 2,
    hint: "Usar o verbo modal 'should' é uma forma muito comum de pedir conselhos.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Hard",
    text: "You want to interrupt a conversation politely. What can you say?",
    options: ["Stop talking!", "Listen to me.", "Can I say something?", "Sorry to interrupt, but..."],
    correctOption: 3,
    hint: "Pedir desculpa pela interrupção é a forma mais educada de entrar numa conversa.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you politely decline an invitation to a party?",
    options: ["No, I don't want to go.", "I'm busy.", "That's a bad idea.", "I'd love to, but I'm afraid I have other plans."],
    correctOption: 3,
    hint: "Uma recusa educada inclui frequentemente um comentário positivo primeiro, seguido de uma razão ou desculpa.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Easy",
    text: "How do you describe your plans for the weekend?",
    options: ["I'm going to visit my family.", "I visit my family.", "I did visit my family.", "I was visiting my family."],
    correctOption: 0,
    hint: "A estrutura 'be going to' é perfeita para falar de planos futuros.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Medium",
    text: "You are talking about a past experience. Choose the best opening phrase.",
    options: ["One time, I go...", "I remember when I went...", "I will go...", "I'm going..."],
    correctOption: 1,
    hint: "Esta frase sinaliza claramente que estás prestes a contar uma história do passado.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Easy",
    text: "How do you agree with someone's opinion?",
    options: ["I'm not sure.", "I don't think so.", "I suppose so.", "That's not right."],
    correctOption: 2,
    hint: "Esta é uma frase comum para mostrar que concordas, talvez não com muita força.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the best way to ask about someone's health.",
    options: ["Are you sick?", "What's your problem?", "How have you been feeling?", "You don't look good."],
    correctOption: 2,
    hint: "Esta é uma forma geral e educada de perguntar pelo bem-estar de alguém.",
  },
  {
    cefrLevel: "B1",
    area: "Speaking",
    difficulty: "Hard",
    text: "You need someone to speak more slowly. What is the most polite way to ask?",
    options: ["Speak slow!", "You're too fast.", "Could you please speak a bit more slowly?", "I don't understand you."],
    correctOption: 2,
    hint: "Usar 'Could you please...' torna o pedido muito educado.",
  },

  // B1 - Writing (10 questions)
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Easy",
    text: "You are writing an email to a hotel to ask for information. What is a good subject line?",
    options: ["My Email", "Question", "Information about your hotel", "Inquiry about a reservation"],
    correctOption: 3,
    hint: "Um bom assunto de e-mail é específico e formal. 'Inquiry' é uma boa palavra formal para 'pergunta'.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Medium",
    text: "Choose the best opening for a semi-formal email to someone you don't know well.",
    options: ["Hi there,", "Hey,", "What's up,", "Dear Mr. Smith,"],
    correctOption: 3,
    hint: "Usar 'Dear' seguido de um título (Mr., Ms., Dr.) e apelido é o padrão para comunicação formal e semi-formal.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Medium",
    text: "Which sentence correctly connects a cause and an effect?",
    options: ["The game was cancelled due to the rain.", "The game was cancelled, it was raining.", "Because the rain, the game was cancelled.", "The rain, so the game was cancelled."],
    correctOption: 0,
    hint: "A expressão 'due to' é uma forma comum de ligar um resultado à sua causa.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Hard",
    text: "You are writing a product review. How can you structure your main paragraph?",
    options: ["First, I will say I hate it. Second, it's bad.", "I will talk about the price. Also the color. The features.", "Start with a general opinion, then provide specific pros and cons.", "List all the features without any comments."],
    correctOption: 2,
    hint: "Uma boa estrutura de parágrafo apresenta uma ideia principal e depois apoia-a com detalhes.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Hard",
    text: "Choose the sentence that gives advice without being too direct.",
    options: ["You must exercise more.", "You should exercise more.", "If I were you, I would exercise more.", "Why don't you exercise more?"],
    correctOption: 2,
    hint: "O second conditional ('If I were you...') é uma forma comum e educada de dar conselhos.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Easy",
    text: "How do you correctly write a date in a formal letter (British English)?",
    options: ["10-12-2023", "10/12/2023", "12-10-2023", "10 December 2023"],
    correctOption: 3,
    hint: "Escrever o nome do mês completo é a forma mais clara e formal.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Medium",
    text: "What is the best concluding phrase for a formal email ending in 'Dear Sir/Madam'?",
    options: ["Best wishes,", "Cheers,", "Yours faithfully,", "All the best,"],
    correctOption: 2,
    hint: "Quando não conheces o nome do destinatário, 'Yours faithfully,' é o fecho formal tradicional.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Easy",
    text: "Which sentence uses a comparative adjective correctly?",
    options: ["This book is more interesting as that one.", "This book is interesting than that one.", "This book is more interesting than that one.", "This book is interestinger than that one."],
    correctOption: 2,
    hint: "Para adjetivos longos, usa 'more...than' para formar o comparativo.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Medium",
    text: "You are writing a story. Which sentence creates the most suspense?",
    options: ["Everything was normal.", "Suddenly, the lights went out.", "He opened the door and saw his friend.", "It was a sunny day."],
    correctOption: 1,
    hint: "Palavras como 'suddenly' e eventos inesperados são ótimos para criar suspense.",
  },
  {
    cefrLevel: "B1",
    area: "Writing",
    difficulty: "Hard",
    text: "You want to link two contrasting ideas in one sentence. Which conjunction is most appropriate?",
    options: ["I enjoyed the film, and the acting was terrible.", "I enjoyed the film, so the acting was terrible.", "I enjoyed the film, although the acting was terrible.", "I enjoyed the film, because the acting was terrible."],
    correctOption: 2,
    hint: "'Although' (ou 'though'/'even though') é usado para ligar duas ideias contrastantes ou surpreendentes.",
  },
];
