export const b2Questions = [
  // B2 - Grammar (10 questions)
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Easy",
    text: "By the time the firefighters arrived, the building ___ completely burned down.",
    options: ["has", "was", "had", "is"],
    correctOption: 2,
    hint: "Use the Past Perfect to emphasize that one past action was completed before another past action started.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Medium",
    text: "___ I known about your situation, I would have offered to help.",
    options: ["If", "When", "Had", "Should"],
    correctOption: 2,
    hint: "This is an inverted third conditional, used for formal emphasis. The 'if' is omitted.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Medium",
    text: "Not only ___ the concert, but they also met the band backstage.",
    options: ["they enjoyed", "did they enjoy", "they did enjoy", "have they enjoyed"],
    correctOption: 1,
    hint: "When a sentence starts with 'Not only', we use inversion: auxiliary verb + subject + main verb.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Hard",
    text: "The new regulations, ___ have been approved by the board, will be implemented next month.",
    options: ["that", "which", "who", "what"],
    correctOption: 1,
    hint: "Use 'which' in a non-defining relative clause (between commas) to add extra information about a thing.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Hard",
    text: "I wish I ___ more attention during the lecture yesterday.",
    options: ["paid", "have paid", "would pay", "had paid"],
    correctOption: 3,
    hint: "To express a regret about a past situation, use 'I wish' + Past Perfect.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Easy",
    text: "The report is expected ___ submitted by the end of the day.",
    options: ["be", "to be", "being", "to being"],
    correctOption: 1,
    hint: "The passive structure 'is expected' is followed by a 'to-infinitive'.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Medium",
    text: "He is considered ___ one of the best authors of his generation.",
    options: ["being", "to be", "be", "as"],
    correctOption: 1,
    hint: "The passive verb 'is considered' is often followed by a 'to-infinitive'.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Hard",
    text: "No matter how hard he ___, he couldn't open the jar.",
    options: ["tries", "tried", "would try", "has tried"],
    correctOption: 1,
    hint: "In this structure expressing repeated effort in the past, the simple past is used.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Easy",
    text: "It's high time you ___ taking this matter seriously.",
    options: ["start", "to start", "started", "have started"],
    correctOption: 2,
    hint: "The expression 'It's high time' is followed by the past simple to indicate that something should have been done already.",
  },
  {
    cefrLevel: "B2",
    area: "Grammar",
    difficulty: "Medium",
    text: "She insisted on ___ for the meal, even though I offered.",
    options: ["paying", "to pay", "pay", "paid"],
    correctOption: 0,
    hint: "Prepositions, like 'on', are followed by a gerund (-ing form).",
  },

  // B2 - Vocabulary (10 questions)
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "The new manager is trying to ___ a few changes around the office.",
    options: ["bring about", "bring up", "bring in", "bring down"],
    correctOption: 0,
    hint: "This phrasal verb means to cause something to happen.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "I can't ___ with all this noise; it's impossible to concentrate.",
    options: ["put up", "put off", "put in", "put on"],
    correctOption: 0,
    hint: "This phrasal verb means to tolerate or endure something unpleasant.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "The company had to ___ a number of employees due to financial difficulties.",
    options: ["give up", "let down", "lay off", "get away"],
    correctOption: 2,
    hint: "This phrasal verb means to end someone's employment, especially for reasons not related to their performance.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "Her arguments were so ___ that I had to agree with her.",
    options: ["compelling", "recurring", "deceptive", "tedious"],
    correctOption: 0,
    hint: "This adjective means 'evoking interest, attention, or admiration in a powerfully irresistible way'.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "Despite the ___ of the situation, the team remained calm and professional.",
    options: ["gravity", "levity", "simplicity", "velocity"],
    correctOption: 0,
    hint: "This word means 'extreme importance or seriousness'.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "It is ___ to rain later, so you should take an umbrella.",
    options: ["likely", "probably", "possibly", "surely"],
    correctOption: 0,
    hint: "This adjective is used to indicate that something is probable.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "The negotiations broke ___ without any agreement being reached.",
    options: ["up", "out", "in", "down"],
    correctOption: 3,
    hint: "This phrasal verb means to fail or stop functioning, in this case, regarding talks or negotiations.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The problem of climate change requires a ___ solution, involving all nations.",
    options: ["global", "local", "partial", "temporary"],
    correctOption: 0,
    hint: "This adjective means relating to the whole world.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "He finally ___ to his parents that he had failed the exam.",
    options: ["admitted", "accepted", "agreed", "allowed"],
    correctOption: 0,
    hint: "This verb means to confess to be true, often reluctantly.",
  },
  {
    cefrLevel: "B2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "The new film has received ___ reviews from the critics.",
    options: ["overwhelmingly", "underwhelmingly", "partially", "moderately"],
    correctOption: 0,
    hint: "This adverb means 'very strongly or completely'.",
  },

  // B2 - Reading (10 questions)
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the article: 'The mayor has pledged to tackle the city's traffic congestion.' What has the mayor promised to do?",
    options: ["Increase traffic", "Ignore the traffic problem", "Address the issue of traffic jams", "Build more roads"],
    correctOption: 2,
    hint: "'To pledge' means to promise, and 'to tackle' means to deal with a problem. 'Congestion' refers to traffic jams.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'The report highlights the need for immediate action, yet it fails to propose any concrete solutions.' What is the main criticism of the report?",
    options: ["It is too long", "It doesn't provide specific solutions", "It was published too late", "It's not well-written"],
    correctOption: 1,
    hint: "The word 'yet' introduces a contrast. The report does one thing (highlights a need) but fails to do another (propose solutions).",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'Although the initial results were promising, subsequent tests revealed several flaws in the design.' What did the later tests show?",
    options: ["The design was perfect", "The initial results were wrong", "The design had several problems", "The tests were successful"],
    correctOption: 2,
    hint: "'Subsequent' means 'coming after', and 'flaws' means 'faults or weaknesses'.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the excerpt: 'The author's tone is overtly critical of the government's policy, though she concedes that its intentions were sound.' What does the author admit about the policy?",
    options: ["It was a complete failure.", "The government was trying to do the right thing.", "The policy was popular.", "It was a well-designed policy."],
    correctOption: 1,
    hint: "To 'concede' means to admit that something is true, often reluctantly. 'Sound intentions' means good motives.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the review: 'The plot is somewhat derivative, echoing several classic films, but it is executed with such flair that it feels fresh and compelling.' What is the reviewer's overall opinion?",
    options: ["The film is completely unoriginal and boring.", "The film is good despite its lack of originality.", "The film is a classic.", "The film is poorly executed."],
    correctOption: 1,
    hint: "'Derivative' means it's not original. The word 'but' introduces a positive contrast. 'Flair' and 'compelling' are strong positive words.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the instruction: 'All applications must be submitted via the online portal.' How should you submit your application?",
    options: ["By post", "By email", "In person", "Using the website"],
    correctOption: 3,
    hint: "'Via' means 'by way of', and 'online portal' refers to a specific website or web page.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the statement: 'The economic downturn has had a significant impact on small businesses.' What has happened to small businesses?",
    options: ["They have become more successful.", "They have been strongly affected by the bad economy.", "They have not been affected.", "They have received more funding."],
    correctOption: 1,
    hint: "'Downturn' means a decline in economic activity, and 'significant impact' means a powerful effect.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'He was acquitted of all charges, as the prosecution's key evidence was deemed inadmissible in court.' Why was he found not guilty?",
    options: ["He confessed to the crime.", "The jury liked him.", "The main evidence against him couldn't be used.", "There was no evidence."],
    correctOption: 2,
    hint: "'Acquitted' means found not guilty. 'Inadmissible' means that evidence is not allowed to be used in a trial.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'The charity provides invaluable support to families in need.' What kind of support does the charity provide?",
    options: ["Worthless support", "Extremely useful support", "Financial support only", "Temporary support"],
    correctOption: 1,
    hint: "The prefix 'in-' can sometimes mean 'not', but 'invaluable' is a special case meaning 'so valuable that its worth cannot be measured'.",
  },
  {
    cefrLevel: "B2",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the notice: 'This area is under 24-hour surveillance.' What does this mean?",
    options: ["The area is closed at night.", "You must pay to enter this area.", "The area is being constantly watched with cameras.", "The area is a private property."],
    correctOption: 2,
    hint: "'Surveillance' means close observation, especially by cameras.",
  },

  // B2 - Listening (10 questions)
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'I'm afraid the manager is in a meeting at the moment. Can I take a message?').' Why can't the person speak to the manager?",
    options: ["The manager is on holiday.", "The manager is busy in a meeting.", "The manager doesn't want to talk.", "The manager has left for the day."],
    correctOption: 1,
    hint: "The speaker gives a specific reason for the manager's unavailability.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'To be honest, I'm having second thoughts about moving abroad.').' How does the speaker feel about moving abroad?",
    options: ["They are excited and sure about it.", "They are starting to doubt their decision.", "They have already moved.", "They have cancelled their plans."],
    correctOption: 1,
    hint: "'To have second thoughts' means to reconsider a decision you have made.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'Had I known about the road closure, I would have taken a different route.').' What can be inferred from this statement?",
    options: ["The speaker took a different route.", "The speaker knew about the road closure.", "The speaker was probably late.", "The speaker enjoyed the journey."],
    correctOption: 2,
    hint: "This inverted third conditional expresses a past regret. It implies the speaker's journey was negatively affected because they didn't have certain information.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'The concert was supposed to be amazing, but it didn't quite live up to the hype.').' What was the speaker's opinion of the concert?",
    options: ["It was better than expected.", "It was as good as everyone said.", "It was a total disaster.", "It was disappointing and not as good as expected."],
    correctOption: 3,
    hint: "'To live up to the hype' means to be as good as people expected. The speaker says it 'didn't quite' do that.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'I could be wrong, but I get the impression that she's not entirely happy with the new arrangement.').' What does the speaker imply about the woman?",
    options: ["She is very happy with the arrangement.", "She is angry about the arrangement.", "She has not said she is unhappy, but she seems to be.", "She does not understand the arrangement."],
    correctOption: 2,
    hint: "'To get the impression' means to form an idea or opinion without being told directly. It suggests reading between the lines.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'The item is currently out of stock. We should have more in next week.').' What is the status of the item?",
    options: ["It is available now.", "It is on sale.", "It is not available at the moment.", "It has been discontinued."],
    correctOption: 2,
    hint: "'Out of stock' means there are none left to sell.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I've been meaning to call you for ages, but I've been so snowed under with work.').' Why hasn't the speaker called?",
    options: ["They forgot.", "They didn't have the number.", "They have been extremely busy with work.", "They didn't want to call."],
    correctOption: 2,
    hint: "The idiom 'snowed under with work' means to have a very large amount of work to do.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'He's a bit of a dark horse; I had no idea he could play the piano so brilliantly.').' What does the speaker mean by 'a dark horse'?",
    options: ["Someone who is not very talented.", "Someone who is very quiet and shy.", "Someone who has a surprising skill or quality.", "Someone who is not very friendly."],
    correctOption: 2,
    hint: "This idiom refers to someone who surprisingly wins or succeeds, or who has a secret ability.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'All things considered, I think we did a pretty good job.').' What is the speaker's conclusion?",
    options: ["They failed.", "They could have done much better.", "They did a perfect job.", "Overall, their performance was good."],
    correctOption: 3,
    hint: "The phrase 'all things considered' means 'taking everything into account' and is used to give a final summary or judgement.",
  },
  {
    cefrLevel: "B2",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'The film is based on a true story.').' What is the origin of the film's plot?",
    options: ["It is completely fictional.", "It is from a fantasy novel.", "It is adapted from a play.", "It is based on real events."],
    correctOption: 3,
    hint: "A 'true story' refers to events that actually happened.",
  },

  // B2 - Speaking (10 questions)
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Easy",
    text: "How would you express a strong recommendation for a restaurant?",
    options: ["The restaurant is okay.", "You should go to the restaurant.", "You really must try that new Italian restaurant!", "I know a restaurant."],
    correctOption: 2,
    hint: "Using adverbs like 'really' and modal verbs like 'must' adds strength and enthusiasm to a recommendation.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Medium",
    text: "You are discussing a controversial topic and want to politely disagree with someone. What's the best way to phrase it?",
    options: ["That's a stupid idea.", "You're wrong.", "I see your point, but I have a different perspective.", "I don't agree with you at all."],
    correctOption: 2,
    hint: "Acknowledging the other person's point ('I see your point') before stating your own opinion is a key strategy for polite disagreement.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Medium",
    text: "How would you speculate about a past event?",
    options: ["They must be late.", "They might have gotten stuck in traffic.", "They will be late.", "They are late."],
    correctOption: 1,
    hint: "Use 'might have' + past participle to talk about a possibility in the past.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Hard",
    text: "You want to paraphrase what someone has just said to check your understanding. What's a good way to start?",
    options: ["Can you repeat that?", "So, if I understand correctly, you're saying that...", "I don't get it.", "That makes no sense."],
    correctOption: 1,
    hint: "This phrase signals your intention to summarize and confirm, which is an active listening skill.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you tactfully point out a mistake someone has made?",
    options: ["You've made a huge error.", "That's completely wrong.", "I think there might be a slight misunderstanding here.", "You failed."],
    correctOption: 2,
    hint: "Using softening language like 'I think there might be' and 'slight' makes the correction much less direct and more polite.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Easy",
    text: "How would you describe an ongoing action that started in the past and is still continuing?",
    options: ["I work here for two years.", "I have been working here for two years.", "I did work here for two years.", "I am work here for two years."],
    correctOption: 1,
    hint: "The Present Perfect Continuous is used to emphasize the duration of an action that started in the past and continues to the present.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Medium",
    text: "Choose the most natural way to talk about a hypothetical situation in the present.",
    options: ["If I am rich, I would travel the world.", "If I was rich, I would travel the world.", "If I were rich, I would travel the world.", "If I would be rich, I would travel the world."],
    correctOption: 2,
    hint: "In the second conditional, it's common to use 'were' instead of 'was' for all subjects, especially in more formal contexts.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Hard",
    text: "You're in a debate. How would you introduce a counter-argument?",
    options: ["On the other hand, one could argue that...", "Also, another thing...", "But you're wrong because...", "That's not the point."],
    correctOption: 0,
    hint: "Phrases like 'On the other hand' or 'Alternatively' are excellent formal ways to introduce a contrasting viewpoint.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Easy",
    text: "How do you report what someone else said?",
    options: ["She said, 'I am tired.'", "She said me she was tired.", "She told me that she was tired.", "She told that she was tired."],
    correctOption: 2,
    hint: "The verb 'tell' needs an object (e.g., 'me', 'him'), while 'say' does not. In reported speech, tenses often shift back.",
  },
  {
    cefrLevel: "B2",
    area: "Speaking",
    difficulty: "Medium",
    text: "How do you give a two-sided argument, showing both pros and cons?",
    options: ["It's good. It's also bad.", "I like it, but I also don't like it.", "While there are clear advantages, such as..., we also need to consider the drawbacks, for instance...", "It has good and bad."],
    correctOption: 2,
    hint: "Using linking phrases like 'While there are advantages' and 'consider the drawbacks' shows a balanced and structured argument.",
  },

  // B2 - Writing (10 questions)
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Easy",
    text: "Which sentence is correctly structured in the passive voice?",
    options: ["The company was built the factory in 1990.", "The factory was built by the company in 1990.", "The factory built by the company in 1990.", "In 1990, the company was built the factory."],
    correctOption: 1,
    hint: "The passive voice structure is: object + verb 'to be' (in correct tense) + past participle (+ by + subject).",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Medium",
    text: "You are writing a formal report. Which of these phrases is most appropriate?",
    options: ["It's a really big problem.", "The problem is massive.", "This constitutes a significant challenge.", "We've got a big issue here."],
    correctOption: 2,
    hint: "Formal writing uses more sophisticated vocabulary like 'constitutes' and 'significant challenge' instead of informal words.",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Medium",
    text: "Choose the sentence with the correct use of a non-defining relative clause.",
    options: ["My brother who lives in London is a doctor.", "My brother, who lives in London, is a doctor.", "My brother that lives in London is a doctor.", "My brother, that lives in London, is a doctor."],
    correctOption: 1,
    hint: "A non-defining clause adds extra, non-essential information and is separated by commas. 'That' cannot be used in these clauses.",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Hard",
    text: "You are writing an essay. What is the main purpose of a topic sentence?",
    options: ["To provide a detailed example.", "To conclude the paragraph.", "To introduce the main idea of the paragraph.", "To ask the reader a question."],
    correctOption: 2,
    hint: "The topic sentence is usually the first sentence of a paragraph and it tells the reader what the paragraph will be about.",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Hard",
    text: "Which sentence provides the most effective and formal transition between a problem and a solution in an essay?",
    options: ["Now for the good part.", "So, what can we do?", "To address this issue, several measures can be implemented.", "And the solution is..."],
    correctOption: 2,
    hint: "Formal essays use clear and structured transition phrases. 'To address this issue' is a sophisticated way to introduce solutions.",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Easy",
    text: "Which of these is a common feature of a formal letter?",
    options: ["Using slang and emojis", "Using contractions like 'don't' and 'can't'", "A clear, concise subject line", "Starting with 'Hey'"],
    correctOption: 2,
    hint: "Formal communication requires clarity and professionalism from the very beginning.",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Medium",
    text: "You want to express cause and effect in a formal way. Which is the best option?",
    options: ["The company cut costs, so it was more profitable.", "The company's increased profitability was a direct result of cost-cutting measures.", "The company made more profit because it cut costs.", "Cutting costs made the company more profitable."],
    correctOption: 1,
    hint: "Using noun phrases like 'increased profitability' and 'cost-cutting measures' makes the sentence more formal and academic.",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Hard",
    text: "When writing a for-and-against essay, what is crucial for a balanced argument?",
    options: ["Only presenting the arguments you agree with.", "Giving equal and objective consideration to both sides of the issue.", "Focusing mainly on the negative aspects.", "Writing a very strong, one-sided conclusion."],
    correctOption: 1,
    hint: "A balanced essay must explore both the pros and cons of a topic fairly before reaching a conclusion.",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Easy",
    text: "Which sentence correctly uses the present perfect for a recent past action with present relevance?",
    options: ["I have lost my keys and now I can't get into my house.", "I lost my keys yesterday.", "I was losing my keys.", "I lose my keys."],
    correctOption: 0,
    hint: "The present perfect connects a past event (losing the keys) with a present result (not being able to get in).",
  },
  {
    cefrLevel: "B2",
    area: "Writing",
    difficulty: "Medium",
    text: "Which sentence shows a future plan that was made in the past?",
    options: ["I am going to a concert tomorrow.", "I went to a concert yesterday.", "I was going to go to the concert, but it was cancelled.", "I will go to a concert."],
    correctOption: 2,
    hint: "The 'was/were going to' structure is used to talk about past plans, especially those that didn't happen.",
  },
];
