export const c1Questions = [
  // C1 - Grammar (10 questions)
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Easy",
    text: "___ had I left the house than it started to pour with rain.",
    options: ["As soon as", "No sooner", "Hardly", "Right after"],
    correctOption: 1,
    hint: "This is a formal inversion structure used to emphasize that one thing happened immediately after another. It's paired with 'than'.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Medium",
    text: "It is imperative that she ___ informed of the changes immediately.",
    options: ["is", "be", "was", "to be"],
    correctOption: 1,
    hint: "After expressions like 'it is imperative/vital/essential that...', we use the subjunctive mood, which is the base form of the verb.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Medium",
    text: "___ being an accomplished pianist, he is also a talented composer.",
    options: ["Besides", "Despite", "Although", "In addition"],
    correctOption: 0,
    hint: "Which word means 'in addition to' and is followed by a gerund (-ing form)?",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Hard",
    text: "What I find most frustrating ___ the lack of communication within the team.",
    options: ["is", "are", "be", "it is"],
    correctOption: 0,
    hint: "This is a cleft sentence. The entire 'What...' clause acts as the subject, which is singular.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Hard",
    text: "He is said ___ a fortune in the stock market in the 1990s.",
    options: ["to make", "making", "to have made", "having made"],
    correctOption: 2,
    hint: "Use a perfect infinitive ('to have' + past participle) to refer to a past action in reporting structures like 'is said to...'.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Easy",
    text: "Were you ___ finish early, you could join us for dinner.",
    options: ["to", "able", "would", "could"],
    correctOption: 0,
    hint: "This is an inverted conditional structure: 'Were + subject + to-infinitive'. It's a more formal way of saying 'If you were to...'.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Medium",
    text: "The committee is composed of people from ___ walks of life.",
    options: ["every", "all", "various", "each"],
    correctOption: 1,
    hint: "The idiom 'all walks of life' means from many different backgrounds and professions.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Hard",
    text: "___ the cost, the project was a resounding success.",
    options: ["Regardless", "Despite", "Even though", "Albeit"],
    correctOption: 1,
    hint: "'Despite' and 'In spite of' are followed by a noun or noun phrase. 'Although' is followed by a clause.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Easy",
    text: "I would rather you ___ that to me in front of my boss.",
    options: ["didn't say", "don't say", "hadn't said", "wouldn't say"],
    correctOption: 2,
    hint: "The structure 'would rather + subject + past perfect' is used to express a preference about a past action.",
  },
  {
    cefrLevel: "C1",
    area: "Grammar",
    difficulty: "Medium",
    text: "The reason ___ he was late is that there was a traffic jam.",
    options: ["because", "for", "due to", "why"],
    correctOption: 3,
    hint: "In this structure, 'the reason why' is the standard and most natural-sounding collocation.",
  },

  // C1 - Vocabulary (10 questions)
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "The new CEO's speech was designed to ___ the employees' fears about restructuring.",
    options: ["allay", "provoke", "amplify", "justify"],
    correctOption: 0,
    hint: "This verb means to diminish or put at rest (fear, suspicion, or worry).",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "She gave a ___ shrug, pretending she didn't care about the news.",
    options: ["nonchalant", "concerned", "frantic", "vibrant"],
    correctOption: 0,
    hint: "This adjective describes a feeling or appearance of being casually calm and relaxed.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "The evidence was ___; there was no doubt about who was guilty.",
    options: ["inconclusive", "irrefutable", "ambiguous", "circumstantial"],
    correctOption: 1,
    hint: "This adjective means 'impossible to deny or disprove'.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The politician's ___ speech was full of empty promises and clichés.",
    options: ["cogent", "succinct", "verbose", "platitudinous"],
    correctOption: 3,
    hint: "This adjective describes a remark or statement that is dull and has been used too often to be interesting or thoughtful.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "He tends to ___ when discussing his achievements, often exaggerating their importance.",
    options: ["equivocate", "pontificate", "reciprocate", "aggrandize"],
    correctOption: 3,
    hint: "This verb means to increase the power, status, or wealth of; or to enhance the reputation of (someone) beyond what is justified by the facts.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "The two countries finally agreed to ___ hostilities and sign a peace treaty.",
    options: ["cease", "commence", "escalate", "initiate"],
    correctOption: 0,
    hint: "This verb means to bring or come to an end.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "Her ___ nature made her an excellent diplomat.",
    options: ["gregarious", "taciturn", "pugnacious", "fastidious"],
    correctOption: 0,
    hint: "This adjective describes a person who is fond of company; sociable.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The novel's plot was so ___ that I couldn't follow it.",
    options: ["straightforward", "convoluted", "transparent", "linear"],
    correctOption: 1,
    hint: "This adjective means 'extremely complex and difficult to follow'.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "It is ___ that you complete this form before the deadline.",
    options: ["trivial", "optional", "crucial", "suggested"],
    correctOption: 2,
    hint: "This adjective means 'decisive or critical, especially in the success or failure of something'.",
  },
  {
    cefrLevel: "C1",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "The company's decision to downsize was a ___ pill for the employees to swallow.",
    options: ["sweet", "bitter", "sour", "salty"],
    correctOption: 1,
    hint: "This idiom refers to a difficult or unpleasant fact that has to be accepted.",
  },

  // C1 - Reading (10 questions)
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the text: 'The treaty was ratified by all member states, thereby making it legally binding.' What is the consequence of the treaty's ratification?",
    options: ["It became optional.", "It became legally enforceable.", "It was rejected.", "It needed more discussion."],
    correctOption: 1,
    hint: "'Ratified' means formally approved, and 'legally binding' means it must be obeyed by law.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the excerpt: 'The author juxtaposes the tranquility of the countryside with the chaotic urban sprawl, creating a stark contrast.' What technique does the author use?",
    options: ["Foreshadowing", "Placing two contrasting things side by side", "Using metaphors", "Detailed descriptions"],
    correctOption: 1,
    hint: "'To juxtapose' means to place different things together in order to create an interesting effect or to show how they are the same or different.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'His arguments, albeit well-articulated, failed to address the core ethical concerns.' What is the writer's main criticism?",
    options: ["His arguments were not well-articulated.", "His arguments were unethical.", "His arguments were convincing.", "His arguments missed the main ethical points."],
    correctOption: 3,
    hint: "'Albeit' is a formal way of saying 'although'. It introduces a concession before the main point of criticism.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'The consensus among climate scientists is unequivocal: the planet is warming at an unprecedented rate.' What does the text imply about the scientists' views?",
    options: ["Scientists are divided on the issue.", "Scientists are unsure about the rate of warming.", "Scientists almost universally agree on the warming trend.", "Scientists believe the warming rate is normal."],
    correctOption: 2,
    hint: "'Consensus' means general agreement. 'Unequivocal' means leaving no doubt. 'Unprecedented' means never done or known before.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the critique: 'The film's narrative is hampered by a surfeit of underdeveloped subplots, which detract from the main story's impact.' What is the primary flaw identified?",
    options: ["The main story is weak.", "There are too many subplots that aren't properly explored.", "The acting is poor.", "The film is too short."],
    correctOption: 1,
    hint: "'A surfeit' means an excessive amount of something. 'Underdeveloped' means not fully realized. 'To detract from' means to reduce the value of something.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the policy document: 'All personnel must adhere to the new safety protocols without exception.' What is required of the personnel?",
    options: ["They can choose which protocols to follow.", "They should suggest new protocols.", "They must follow all new safety rules.", "The protocols are optional."],
    correctOption: 2,
    hint: "'To adhere to' means to stick to or follow, and 'without exception' means for everyone.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'The ancient civilization's decline was precipitated by a combination of environmental changes and internal conflict.' What caused the decline?",
    options: ["A single catastrophic event.", "A slow, gradual decay.", "Only internal conflict.", "A mix of environmental and social factors."],
    correctOption: 3,
    hint: "'Precipitated by' means caused by, and 'a combination of' indicates multiple factors were involved.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the analysis: 'The market's bullish behavior can be attributed to a confluence of factors, namely low interest rates and high consumer confidence.' What does 'confluence of factors' mean?",
    options: ["A confusing set of factors", "A situation where factors conflict", "A situation where events or circumstances meet or come together", "A decline in contributing factors"],
    correctOption: 2,
    hint: "'Confluence' literally means a place where two rivers meet. Here, it is used metaphorically.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'She has a predilection for spicy food, often adding chili to even the most mundane dishes.' What does 'predilection' mean?",
    options: ["A strong dislike", "An allergy", "A preference or special liking", "A lack of knowledge"],
    correctOption: 2,
    hint: "The context of 'often adding chili' suggests she has a strong liking for something.",
  },
  {
    cefrLevel: "C1",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the statement: 'The findings of the study are tentative and require further research.' What is the status of the study's findings?",
    options: ["They are conclusive and final.", "They are not yet certain or fixed.", "They have been proven wrong.", "They are widely accepted."],
    correctOption: 1,
    hint: "'Tentative' means provisional or not definite.",
  },

  // C1 - Listening (10 questions)
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'Given the circumstances, I think we should postpone the meeting.').' What is being suggested?",
    options: ["Cancelling the meeting", "Starting the meeting early", "Having the meeting online", "Delaying the meeting until a later time"],
    correctOption: 3,
    hint: "'To postpone' means to arrange for something to take place at a time later than that first scheduled.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'He has a tendency to beat around the bush instead of getting straight to the point.').' How does the person being described usually communicate?",
    options: ["He is very direct and clear.", "He avoids talking about the main topic.", "He speaks very quickly.", "He is often rude."],
    correctOption: 1,
    hint: "The idiom 'to beat around the bush' means to avoid talking about what is important.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I'm in two minds about whether to accept the job offer or not.').' What is the speaker's situation?",
    options: ["They have decided to accept the job.", "They have decided to reject the job.", "They are undecided about the job offer.", "They are waiting for a better offer."],
    correctOption: 2,
    hint: "The idiom 'to be in two minds' means to be unable to decide between two options.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'The company's initial statement was deliberately ambiguous, leaving investors to read between the lines.').' What does the speaker imply about the statement?",
    options: ["It was clear and transparent.", "It contained a lot of detail.", "It was intentionally unclear.", "It was a mistake."],
    correctOption: 2,
    hint: "'Ambiguous' means unclear or having more than one possible meaning. 'To read between the lines' means to look for a hidden meaning.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'She's a fantastic public speaker, but her performance in one-on-one negotiations is her Achilles' heel.').' What is the speaker saying about the woman's negotiation skills?",
    options: ["They are her greatest strength.", "They are improving.", "They are a significant weakness.", "They are better than her public speaking."],
    correctOption: 2,
    hint: "An 'Achilles' heel' is a metaphor for a weakness or vulnerable point in an otherwise strong person.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'Let's table this discussion for now and come back to it next week.').' What does the speaker want to do?",
    options: ["Finalize the discussion now", "Forget about the discussion completely", "Postpone the discussion", "Write down the discussion points"],
    correctOption: 2,
    hint: "In this context, 'to table' something means to postpone its consideration.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I take my hat off to him; I wouldn't have had the courage to do that.').' What is the speaker expressing?",
    options: ["Disagreement", "Admiration and respect", "Disappointment", "Sympathy"],
    correctOption: 1,
    hint: "The idiom 'to take one's hat off to someone' is an expression of respect or admiration for an achievement.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'His apology seemed rather perfunctory, as if he was just going through the motions.').' What was the speaker's impression of the apology?",
    options: ["It was very sincere and heartfelt.", "It was loud and clear.", "It was done with little effort or feeling.", "It was long and detailed."],
    correctOption: 2,
    hint: "'Perfunctory' means carried out with a minimum of effort or reflection. 'Going through the motions' is an idiom with a similar meaning.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'On the face of it, the plan seems solid, but I have some reservations.').' What is the speaker's opinion?",
    options: ["The plan is definitely solid.", "The plan is terrible.", "The plan appears good, but there might be hidden problems.", "The plan has no reservations."],
    correctOption: 2,
    hint: "'On the face of it' means 'superficially' or 'from appearances alone'. 'Reservations' means doubts.",
  },
  {
    cefrLevel: "C1",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'We'll have to cut a few corners if we want to finish this project on budget.').' What does the speaker suggest?",
    options: ["Spending more money", "Doing the project perfectly", "Taking shortcuts or doing things less thoroughly to save money", "Working longer hours"],
    correctOption: 2,
    hint: "The idiom 'to cut corners' means to do something in the easiest, cheapest, or fastest way.",
  },

  // C1 - Speaking (10 questions)
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Easy",
    text: "How would you formally introduce a topic for discussion in a meeting?",
    options: ["Let's talk about...", "The first item on the agenda is...", "We need to figure out...", "Here's a thing..."],
    correctOption: 1,
    hint: "Using meeting-specific vocabulary like 'agenda' makes your language sound professional and appropriate.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Medium",
    text: "You want to express a nuanced opinion, acknowledging complexity. How could you start?",
    options: ["It's simple, really...", "The issue is not so black and white; on the one hand...", "It's obviously a bad idea.", "I think..."],
    correctOption: 1,
    hint: "Acknowledging that a topic is not 'black and white' shows a sophisticated understanding and prepares the listener for a balanced argument.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Medium",
    text: "How would you politely challenge someone's assumption in a debate?",
    options: ["That's just wrong.", "Where did you get that idea?", "I'm not sure I'd go that far. Could you elaborate on that point?", "You haven't thought about this."],
    correctOption: 2,
    hint: "This response softens the disagreement ('I'm not sure') and politely asks for more information ('Could you elaborate') instead of being confrontational.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Hard",
    text: "You are summarizing a complex article. What phrase could you use to introduce the main conclusion?",
    options: ["So, the end bit says...", "The thing is...", "In essence, the author argues that...", "Finally, and this is important..."],
    correctOption: 2,
    hint: "'In essence' is a sophisticated way to say 'in its most basic form' or 'fundamentally'.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you add a condition or a disclaimer to a statement you've made?",
    options: ["...but I could be wrong.", "...and that's a fact.", "...having said that, we must also consider...", "...so, there you go."],
    correctOption: 2,
    hint: "'Having said that' is a discourse marker used to introduce a contrasting point or a reservation after you have already made a statement.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Easy",
    text: "How do you report a widely-held belief?",
    options: ["I think that...", "Everyone knows that...", "It is generally acknowledged that...", "I heard somewhere that..."],
    correctOption: 2,
    hint: "Using a formal, passive structure like 'It is acknowledged/believed/said that...' is common in academic and formal speech.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Medium",
    text: "How would you express a preference for one thing over another in a formal context?",
    options: ["I like X more than Y.", "X is better than Y.", "My preference would be for X, primarily because...", "Y is bad, X is good."],
    correctOption: 2,
    hint: "Stating your 'preference' and giving a 'primary reason' is a structured and formal way to express your choice.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Hard",
    text: "You are giving a presentation and want to move to the next point. What is a good transition?",
    options: ["And now for the next slide.", "That brings me to my next point, which is...", "Okay, next...", "Moving on..."],
    correctOption: 1,
    hint: "This phrase creates a logical link between the previous point and the new one, making your presentation flow smoothly.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Easy",
    text: "How do you politely interrupt to ask a question?",
    options: ["Excuse me, but I'm a bit unclear on that last point.", "Wait, I don't get it.", "What does that mean?", "Hold on a second."],
    correctOption: 0,
    hint: "This is a polite and professional way to interrupt and ask for clarification without being aggressive.",
  },
  {
    cefrLevel: "C1",
    area: "Speaking",
    difficulty: "Medium",
    text: "How do you propose a hypothetical solution to a problem?",
    options: ["What if we tried...?", "We must do this...", "Let's do this now.", "Maybe we can try this..."],
    correctOption: 0,
    hint: "'What if...' is a great way to introduce a hypothetical scenario or suggestion for discussion.",
  },

  // C1 - Writing (10 questions)
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Easy",
    text: "You are writing a proposal. Which of these demonstrates a formal and persuasive tone?",
    options: ["I think this is a good idea you should consider.", "You'd be crazy not to do this.", "This proposal outlines a strategy to enhance efficiency.", "Let's do this, it will be great."],
    correctOption: 2,
    hint: "Formal proposals use objective and professional language, focusing on strategy and outcomes.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Medium",
    text: "In an academic essay, how should you integrate a quote from a source?",
    options: ["Just paste the quote in a new paragraph.", "As Smith says, '...'", "Smith (2021) argues that '...' (p. 45).", "Smith wrote this: '...'"],
    correctOption: 2,
    hint: "Academic writing requires proper citation, including the author, year, and page number, and integrating the quote into your own sentence.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Medium",
    text: "Which sentence uses a participle clause correctly to add information?",
    options: ["The man sat on the bench and he was reading a book.", "Sitting on the bench, the man was reading a book.", "The man, he was sitting on the bench reading a book.", "The man sat on the bench, was reading a book."],
    correctOption: 1,
    hint: "A participle clause can be used at the beginning of a sentence to provide more information about the subject of the main clause.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Hard",
    text: "You are writing a letter of complaint. What is a key element to include for a successful outcome?",
    options: ["An angry and emotional tone.", "Vague descriptions of the problem.", "Threats of legal action.", "A clear statement of the desired resolution."],
    correctOption: 3,
    hint: "Besides describing the problem, a good complaint letter clearly states what you want the company to do (e.g., a refund, a replacement).",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Hard",
    text: "Which sentence correctly uses an appositive to rename a noun?",
    options: ["My brother, who is a doctor, lives in London.", "My brother, a doctor, lives in London.", "My brother that is a doctor lives in London.", "My brother is a doctor and lives in London."],
    correctOption: 1,
    hint: "An appositive is a noun or noun phrase that renames another noun right beside it. It is usually set off by commas.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Easy",
    text: "What is the purpose of a thesis statement in an essay?",
    options: ["To provide a general overview of the topic.", "To present the main argument or point of the essay.", "To list all the sources used.", "To ask a rhetorical question."],
    correctOption: 1,
    hint: "The thesis statement is a concise summary of the main point or claim of the essay.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Medium",
    text: "Which of the following demonstrates the most formal and academic vocabulary?",
    options: ["The study found out some cool things.", "The investigation's findings indicate several key trends.", "The stuff we found in the study was neat.", "We got some interesting results from the study."],
    correctOption: 1,
    hint: "Words like 'investigation', 'findings', and 'indicate' are standard in academic and formal writing.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Hard",
    text: "How can you effectively concede a point in a persuasive essay?",
    options: ["By ignoring opposing arguments completely.", "By stating that all opposing arguments are wrong.", "Admittedly, there is some merit to the opposing view; however...", "By briefly mentioning an opposing view and dismissing it without analysis."],
    correctOption: 2,
    hint: "Conceding a point ('Admittedly...') and then refuting it ('however...') shows that you have considered the issue deeply and makes your own argument stronger.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Medium",
    text: "Which sentence correctly uses a cleft structure for emphasis?",
    options: ["The bad weather was the reason for the delay.", "What caused the delay was the bad weather.", "The delay was because of the bad weather.", "The bad weather caused the delay, it did."],
    correctOption: 1,
    hint: "Cleft sentences (e.g., starting with 'What...' or 'It is...') are used to focus attention on a particular part of the sentence.",
  },
  {
    cefrLevel: "C1",
    area: "Writing",
    difficulty: "Easy",
    text: "You are concluding a formal report. What is a suitable concluding phrase?",
    options: ["And that's all, folks!", "To wrap it all up...", "In conclusion, the data suggests that...", "So, there you have it."],
    correctOption: 2,
    hint: "Formal conclusions often start with standard signposting phrases like 'In conclusion,' 'To summarize,' or 'In summary'.",
  },
];
