export const c2Questions = [
  // C2 - Grammar (10 questions)
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Easy",
    text: "Seldom ___ such a breathtaking performance.",
    options: ["I have seen", "I saw", "have I seen", "did I see"],
    correctOption: 2,
    hint: "In formal English, when a sentence begins with a negative or limiting adverb like 'Seldom', we invert the subject and auxiliary verb.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Medium",
    text: "___ that he is, he was unable to solve the simple puzzle.",
    options: ["Genius", "A genius", "Genius though", "Though a genius"],
    correctOption: 2,
    hint: "The structure 'Noun + though/as + subject + verb' is an advanced way of expressing contrast, meaning 'Even though he is a genius...'.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Medium",
    text: "The professor insisted that all essays ___ in by Friday, no exceptions.",
    options: ["are handed", "were handed", "be handed", "to be handed"],
    correctOption: 2,
    hint: "This is a classic example of the mandative subjunctive, used after verbs of command or insistence like 'insist that...'.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Hard",
    text: "But for his timely intervention, the situation ___ far worse.",
    options: ["would be", "would have been", "was", "had been"],
    correctOption: 1,
    hint: "'But for...' is a sophisticated alternative to an 'if' clause in the third conditional, meaning 'If it hadn't been for...'.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Hard",
    text: "It's a shame you can't come. I'd sooner you ___ there with us.",
    options: ["are", "were", "had been", "would be"],
    correctOption: 1,
    hint: "The structure 'would sooner/rather + subject' is followed by the subjunctive past to talk about preferences for the present or future.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Easy",
    text: "All decisions, ___ of their immediate impact, must be approved by the board.",
    options: ["irrespective", "irrelevant", "disregarding", "without"],
    correctOption: 0,
    hint: "'Irrespective of' is a formal phrase meaning 'regardless of' or 'without taking into account'.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Medium",
    text: "He finally acquiesced, ___ reluctantly, to the new terms.",
    options: ["despite", "albeit", "whereas", "nonetheless"],
    correctOption: 1,
    hint: "'Albeit' is a formal conjunction used to introduce a fact or comment that reduces the force of what you have just said. It means 'though'.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Hard",
    text: "___ I to be offered the position, I would gratefully accept.",
    options: ["If", "Should", "Had", "Were"],
    correctOption: 3,
    hint: "This is a highly formal inverted second conditional: 'Were + subject + to-infinitive...', equivalent to 'If I were to be offered...'.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Medium",
    text: "The film, the director of ___ is widely acclaimed, won several awards.",
    options: ["that", "which", "whom", "who"],
    correctOption: 2,
    hint: "Use 'whom' as the object of a preposition ('of whom') when referring to people in a formal relative clause.",
  },
  {
    cefrLevel: "C2",
    area: "Grammar",
    difficulty: "Easy",
    text: "The plan, ___ it may seem, is fraught with risk.",
    options: ["as ingenious", "ingenious as", "so ingenious", "ingenious that"],
    correctOption: 1,
    hint: "The structure 'Adjective + as + subject + verb' is a formal way to express contrast, similar to 'Although it may seem ingenious...'.",
  },

  // C2 - Vocabulary (10 questions)
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "His ___ speech at the conference earned him a standing ovation.",
    options: ["soporific", "turgid", "trenchant", "scintillating"],
    correctOption: 3,
    hint: "This adjective means 'sparkling or shining brightly' or 'brilliantly and excitingly clever or skilful'.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "The old library was a ___ of dusty tomes and forgotten manuscripts.",
    options: ["repository", "refectory", "depository", "directory"],
    correctOption: 0,
    hint: "This word means a place where things are stored, particularly a place where a large quality of something is found.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "She had a ___ for saying the right thing at the right time.",
    options: ["knack", "foible", "penchant", "quirk"],
    correctOption: 0,
    hint: "This word means an acquired or natural skill at performing a task.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The politician's speech was a ___ of half-truths and blatant lies.",
    options: ["paradigm", "litany", "panoply", "hodgepodge"],
    correctOption: 3,
    hint: "This word means a confused mixture or a jumble.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "He was known for his ___, often donating large sums of money to charity anonymously.",
    options: ["parsimony", "profligacy", "munificence", "avarice"],
    correctOption: 2,
    hint: "This noun means 'the quality or action of being lavishly generous; great generosity'. The other options relate to stinginess or wastefulness.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "The new evidence completely ___ the defendant's alibi.",
    options: ["corroborated", "repudiated", "fabricated", "conflated"],
    correctOption: 0,
    hint: "This verb means 'to confirm or give support to (a statement, theory, or finding)'.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "The team's performance was ___, with moments of brilliance interspersed with careless errors.",
    options: ["consistent", "flawless", "erratic", "methodical"],
    correctOption: 2,
    hint: "This adjective means 'not even or regular in pattern or movement; unpredictable'.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Hard",
    text: "The philosopher's work is a ___ exploration of the nature of consciousness.",
    options: ["cursory", "magisterial", "superficial", "flippant"],
    correctOption: 1,
    hint: "This adjective means 'having or showing great authority', implying a work of great depth and importance.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Medium",
    text: "Her ___ remarks were a welcome relief in the otherwise tense meeting.",
    options: ["acerbic", "facetious", "caustic", "scathing"],
    correctOption: 1,
    hint: "This adjective describes treating serious issues with deliberately inappropriate humour; it's a kind of light-hearted, sometimes out of place, joking.",
  },
  {
    cefrLevel: "C2",
    area: "Vocabulary",
    difficulty: "Easy",
    text: "The ceasefire is ___, and analysts fear that hostilities could resume at any moment.",
    options: ["robust", "tenuous", "permanent", "unconditional"],
    correctOption: 1,
    hint: "This adjective means 'very weak or slight', suggesting the situation is fragile.",
  },

  // C2 - Reading (10 questions)
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the sentence: 'The committee's decision was a foregone conclusion.' What does this imply?",
    options: ["The decision was a surprise.", "The decision was made without a vote.", "The result was obvious before it was officially decided.", "The committee could not reach a decision."],
    correctOption: 2,
    hint: "A 'foregone conclusion' is a result that can be predicted with certainty.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the excerpt: 'The artist's work eschews categorization, borrowing from disparate movements to create a unique aesthetic.' How is the artist's work described?",
    options: ["It fits neatly into one category.", "It is a poor copy of other styles.", "It is traditional and conventional.", "It avoids being classified by blending different styles."],
    correctOption: 3,
    hint: "'To eschew' means to deliberately avoid using or to abstain from. 'Disparate' means essentially different in kind.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the text: 'The book provides a cursory overview of a vast and complex subject.' What is the nature of the book's overview?",
    options: ["It is extremely detailed and thorough.", "It is hasty and therefore not thorough or detailed.", "It is the definitive work on the subject.", "It is aimed at experts in the field."],
    correctOption: 1,
    hint: "'Cursory' means done quickly and without enough attention to detail.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the critique: 'While the prose is undeniably felicitous, the novel is ultimately a triumph of style over substance.' What is the main point of the critique?",
    options: ["The novel is poorly written but has a good story.", "The novel's beautiful writing cannot compensate for its lack of a meaningful story.", "The novel is a perfect balance of style and story.", "The novel's substance is its main strength."],
    correctOption: 1,
    hint: "'Felicitous' means well-chosen or pleasing. 'Style over substance' is an idiom that criticizes something for being beautiful on the surface but lacking depth.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the analysis: 'The geopolitical landscape has been irrevocably altered by these events.' What does 'irrevocably altered' mean?",
    options: ["Changed in a way that can be easily reversed.", "Changed in a minor or insignificant way.", "Changed in a way that cannot be undone.", "Temporarily changed."],
    correctOption: 2,
    hint: "'Irrevocable' means not able to be changed, reversed, or recovered; final.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the text: 'The new law is a draconian measure aimed at curbing dissent.' How is the new law characterized?",
    options: ["As excessively harsh and severe.", "As liberal and permissive.", "As ineffective.", "As popular and well-received."],
    correctOption: 0,
    hint: "'Draconian' is a strong adjective used to describe laws or measures that are excessively harsh.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the sentence: 'His profligate spending habits led to his eventual bankruptcy.' What caused his bankruptcy?",
    options: ["His careful saving.", "His wise investments.", "His reckless and extravagant spending.", "His lack of income."],
    correctOption: 2,
    hint: "'Profligate' means recklessly extravagant or wasteful in the use of resources.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Hard",
    text: "Read the text: 'The author's polemic against modern capitalism is both scathing and meticulously researched.' What is the nature of the author's work?",
    options: ["A neutral, objective report.", "A strong verbal or written attack on a topic.", "A fictional story about capitalism.", "A celebration of modern capitalism."],
    correctOption: 1,
    hint: "A 'polemic' is a strong attack on someone or something. 'Scathing' means witheringly scornful; severely critical.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Medium",
    text: "Read the description: 'She was a protean actress, equally at home in comedy, drama, and musical theatre.' What does 'protean' mean?",
    options: ["Amateur and inexperienced", "Specialized in one genre", "Consistently playing the same type of character", "Versatile and able to change easily"],
    correctOption: 3,
    hint: "The word comes from the Greek god Proteus, who could change his shape at will. The examples given (comedy, drama, etc.) illustrate this versatility.",
  },
  {
    cefrLevel: "C2",
    area: "Reading",
    difficulty: "Easy",
    text: "Read the sentence: 'The two statements are not mutually exclusive; a person can be both ambitious and compassionate.' What does 'mutually exclusive' mean?",
    options: ["They are always found together.", "They are related to each other.", "They are the same thing.", "They cannot both be true or exist at the same time."],
    correctOption: 3,
    hint: "If two things are mutually exclusive, the presence of one rules out the possibility of the other.",
  },

  // C2 - Listening (10 questions)
  {
    slug: "listening-c2-01",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'Let's not get bogged down in the minutiae; we need to focus on the overarching strategy.').' What does the speaker want to avoid?",
    options: ["Discussing the main strategy", "Making a decision quickly", "Focusing on small, precise details", "Finishing the meeting"],
    correctOption: 2,
    hint: "'To get bogged down' means to be prevented from making progress. 'Minutiae' refers to the small, precise details of something.",
  },
  {
    slug: "listening-c2-02",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'I think he's playing devil's advocate. He doesn't actually believe that, he just wants to provoke a proper debate.').' Why is the person expressing an unpopular opinion?",
    options: ["Because he truly believes it.", "Because he wants to end the conversation.", "To test the strength of the opposing arguments.", "Because he is confused."],
    correctOption: 2,
    hint: "To 'play devil's advocate' is to express an opinion that one does not necessarily agree with, in order to make a discussion more interesting.",
  },
  {
    slug: "listening-c2-03",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'The project was given the green light last week, so we're all systems go.').' What is the status of the project?",
    options: ["It has been cancelled.", "It has been paused.", "It has been officially approved and has started.", "It is still in the planning phase."],
    correctOption: 2,
    hint: "'To be given the green light' is an idiom meaning to be given permission to start something.",
  },
  {
    slug: "listening-c2-04",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'His comments were a thinly veiled critique of the management's new policy.').' What is implied about his comments?",
    options: ["They were openly and directly critical.", "They praised the new policy.", "They were a poorly disguised criticism.", "They were difficult to understand."],
    correctOption: 2,
    hint: "A 'thinly veiled' comment is one that is presented in an indirect way, but whose true meaning is still obvious.",
  },
  {
    slug: "listening-c2-05",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'It's a Hobson's choice, really. Neither option is appealing, but we have to pick one.').' What kind of choice is it?",
    options: ["A choice between two equally good options.", "A choice with no real alternative; you must accept what is offered.", "A choice that must be made quickly.", "A choice that is easy to make."],
    correctOption: 1,
    hint: "A 'Hobson's choice' is a free choice in which only one thing is offered. The phrase implies a 'take it or leave it' scenario.",
  },
  {
    slug: "listening-c2-06",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'In hindsight, I probably should have handled the situation differently.').' What is the speaker doing?",
    options: ["Predicting the future", "Describing a current event", "Reflecting on a past event with new understanding", "Denying any mistakes"],
    correctOption: 2,
    hint: "'Hindsight' is the understanding of a situation or event only after it has happened or developed.",
  },
  {
    slug: "listening-c2-07",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'We have to address the elephant in the room: the budget cuts.').' What is 'the elephant in the room'?",
    options: ["A minor issue", "An obvious major problem that no one wants to discuss", "A secret that only the speaker knows", "A topic for the next meeting"],
    correctOption: 1,
    hint: "This idiom refers to a major problem or controversial issue that is present but ignored by everyone.",
  },
  {
    slug: "listening-c2-08",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Hard",
    text: "Listen to the audio transcript: '(Audio: 'She's a veritable polymath, fluent in five languages and an expert in quantum physics.').' What does 'polymath' mean?",
    options: ["A person who is good at mathematics.", "A person who has studied many languages.", "A person of wide-ranging knowledge or learning.", "A person who is a professional physicist."],
    correctOption: 2,
    hint: "'Poly-' means 'many' and 'math' relates to learning. The examples given (languages, physics) demonstrate a wide range of knowledge.",
  },
  {
    slug: "listening-c2-09",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Medium",
    text: "Listen to the audio transcript: '(Audio: 'The CEO's resignation came completely out of the blue.').' How did the CEO's resignation happen?",
    options: ["It was long expected.", "It happened after a long illness.", "It was announced publicly.", "It happened unexpectedly."],
    correctOption: 3,
    hint: "The idiom 'out of the blue' means completely unexpected.",
  },
  {
    slug: "listening-c2-10",
    cefrLevel: "C2",
    area: "Listening",
    difficulty: "Easy",
    text: "Listen to the audio transcript: '(Audio: 'The two issues are inextricably linked; you can't solve one without addressing the other.').' What is the relationship between the two issues?",
    options: ["They are completely separate.", "They are impossible to separate.", "One is much more important than the other.", "They are easy to solve independently."],
    correctOption: 1,
    hint: "'Inextricably' is an adverb that means in a way that is impossible to disentangle or separate.",
  },

  // C2 - Speaking (10 questions)
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Easy",
    text: "How would you express a firm but polite refusal to a request?",
    options: ["No, I won't.", "That's not possible.", "I'm afraid that won't be feasible at this time.", "Absolutely not."],
    correctOption: 2,
    hint: "Using formal softeners like 'I'm afraid' and formal vocabulary like 'feasible' makes the refusal polite yet clear.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Medium",
    text: "How would you articulate a complex 'cause and effect' relationship in a formal discussion?",
    options: ["This happened because of that.", "The initial event caused the next one.", "The ramifications of the initial decision were twofold...", "When A happened, B happened too."],
    correctOption: 2,
    hint: "'Ramifications' is a sophisticated word for complex consequences, and 'twofold' shows an ability to structure the effects clearly.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Medium",
    text: "How do you elegantly concede a point in a debate without weakening your overall position?",
    options: ["Okay, you're right, I'm wrong.", "I see your point, but it's irrelevant.", "While there is some validity to that argument, it doesn't detract from the overarching issue, which is...", "I guess you have a point there."],
    correctOption: 2,
    hint: "This structure concedes a minor point ('some validity') but immediately pivots back to your main argument ('overarching issue'), showing confidence and control.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Hard",
    text: "How would you hypothesize about an alternative historical outcome?",
    options: ["If things were different, it would be different.", "What if X didn't happen?", "Had the treaty not been signed, it's conceivable that the conflict would have escalated.", "Imagine if things went the other way."],
    correctOption: 2,
    hint: "This uses an advanced inverted conditional ('Had the treaty not been signed...') and sophisticated vocabulary ('conceivable', 'escalated') to discuss a complex counterfactual.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Hard",
    text: "How do you pre-empt a potential counterargument before you even make your main point?",
    options: ["Before you say anything, you're wrong.", "Some of you might be thinking that..., and you'd be right, but...", "I know what you're going to say, and it's not important.", "Now, I'm sure some will argue that... However, this view fails to account for..."],
    correctOption: 3,
    hint: "This advanced debating technique shows you have considered the issue from all angles and allows you to control the narrative by addressing and refuting counterarguments proactively.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Easy",
    text: "How do you express a very strong, personal conviction?",
    options: ["I really, really think that...", "It is my firm belief that...", "I guess I believe that...", "It seems to me that..."],
    correctOption: 1,
    hint: "The phrase 'firm belief' communicates a strong, deeply held conviction in a formal and powerful way.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Medium",
    text: "How would you describe a situation where there is no good outcome?",
    options: ["It's a bad situation.", "We're in a bit of a pickle.", "We find ourselves in a catch-22 situation.", "There are no good options."],
    correctOption: 2,
    hint: "A 'catch-22' is a specific type of no-win situation, a paradoxical dilemma from which there is no escape because of mutually conflicting or dependent conditions.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Hard",
    text: "How would you qualify a statement to show it's only true in specific circumstances?",
    options: ["This is always true.", "This is sometimes true.", "This is true, but only sometimes.", "This holds true, but only insofar as the initial conditions are met."],
    correctOption: 3,
    hint: "The phrase 'insofar as' is a sophisticated conjunction used to specify the extent or degree to which something is true.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Medium",
    text: "How do you begin to summarize a long, complex discussion?",
    options: ["So, to recap...", "To distill the last hour of discussion down to its core points...", "Let's go over that again.", "So, what we said was..."],
    correctOption: 1,
    hint: "'To distill' something means to extract its most essential meaning or features, which is a very precise and impressive way to begin a summary.",
  },
  {
    cefrLevel: "C2",
    area: "Speaking",
    difficulty: "Easy",
    text: "How do you express that something is the most important factor?",
    options: ["The main thing is...", "First of all...", "What it all boils down to is...", "The top thing is..."],
    correctOption: 2,
    hint: "The idiom 'to boil down to something' means to have something as a main or essential part.",
  },

  // C2 - Writing (10 questions)
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Easy",
    text: "In formal academic writing, which of the following is generally discouraged?",
    options: ["Use of the passive voice", "Complex sentence structures", "Use of rhetorical questions", "Citation of sources"],
    correctOption: 2,
    hint: "While used in speeches, rhetorical questions are often seen as informal and less analytical than direct statements in academic prose.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Medium",
    text: "What is the function of the phrase 'mutatis mutandis' in legal or academic texts?",
    options: ["To signal a main point.", "To indicate that something is a direct quote.", "To indicate that necessary changes will be made before applying a statement to a different situation.", "To show that the following point is an example."],
    correctOption: 2,
    hint: "It is a Latin phrase meaning 'the necessary changes having been made'.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Medium",
    text: "Which sentence demonstrates the most sophisticated and nuanced use of concession?",
    options: ["Although the study has limitations, it is still useful.", "The study has limitations but it's good.", "The study's limitations, while not insignificant, do not wholly undermine its central thesis.", "The study has some problems, however it is still important."],
    correctOption: 2,
    hint: "This sentence uses advanced vocabulary ('insignificant', 'undermine', 'central thesis') and a parenthetical concession ('while not insignificant') for a highly formal and analytical tone.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Hard",
    text: "You are writing a critical review. Which sentence best exemplifies a 'damning with faint praise' critique?",
    options: ["The film was an unmitigated disaster.", "The director's ambition, at least, cannot be faulted.", "This is the most brilliant film of the decade.", "The cinematography was breathtakingly beautiful."],
    correctOption: 1,
    hint: "'Damning with faint praise' is a rhetorical technique where you criticize something by praising it so slightly that it's clear you think it's bad. Praising only the 'ambition' implies the execution was a failure.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Hard",
    text: "What is the primary purpose of an abstract in an academic paper?",
    options: ["To serve as a personal introduction of the author.", "To provide a comprehensive, self-contained summary of the entire paper.", "To list the table of contents.", "To present the raw data used in the research."],
    correctOption: 1,
    hint: "An abstract allows readers to quickly understand the paper's purpose, methods, results, and conclusions without reading the full text.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Easy",
    text: "Which sentence correctly uses an ellipsis (...) in formal writing?",
    options: ["I don't know... maybe we should go.", "The report stated, 'The results were... inconclusive.'", "I feel so... tired.", "Wait for it..."],
    correctOption: 1,
    hint: "In formal writing, an ellipsis is primarily used to indicate the omission of words from a direct quotation.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Medium",
    text: "How would you best rephrase 'The writer talks about the problems' for a C2-level academic essay?",
    options: ["The writer mentions the issues.", "The author brings up some bad points.", "The author's treatise elucidates the myriad challenges inherent in the situation.", "The writer tells us about the difficulties."],
    correctOption: 2,
    hint: "This option uses highly advanced and precise vocabulary ('treatise', 'elucidates', 'myriad challenges', 'inherent') appropriate for a proficiency-level analysis.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Hard",
    text: "What is the function of a 'non sequitur' in argumentation?",
    options: ["It is a conclusion that logically follows from the premises.", "It is a form of deductive reasoning.", "It is a conclusion or statement that does not logically follow from the previous argument or statement.", "It is a supporting piece of evidence."],
    correctOption: 2,
    hint: "'Non sequitur' is Latin for 'it does not follow'. It's considered a logical fallacy.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Medium",
    text: "Which sentence uses 'whom' correctly in a highly formal style?",
    options: ["The prize will be given to whomever finishes first.", "Whom is responsible for this decision?", "The artist, whom I have long admired, has a new exhibition.", "Whom do you think you are?"],
    correctOption: 2,
    hint: "'Whom' is the object of the verb 'admired'. You can test this by rephrasing: 'I have long admired him/her (not he/she)'.",
  },
  {
    cefrLevel: "C2",
    area: "Writing",
    difficulty: "Easy",
    text: "When citing sources, what does 'et al.' signify?",
    options: ["And other things", "For example", "In the same place", "And others"],
    correctOption: 3,
    hint: "It is an abbreviation of the Latin phrase 'et alia', used when referring to a number of people.",
  },
];
